//! BACnet Engineering Units
//!
//! This module defines the complete set of engineering units as specified in
//! ISO 16484-5:2017 page 791 (ASHRAE Standard 135-2020).
//!
//! The enum includes all standard BACnet engineering units with their exact
//! numeric values for protocol compatibility.

/// BACnet Engineering Units enumeration
///
/// Represents all engineering units defined in the BACnet standard.
/// Values 0-255 and 47808-49999 are reserved for definition by ASHRAE.
/// Values 256-47807 and 50000-65535 may be used by others and are represented
/// by the `Other(u32)` variant.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Default)]
pub enum EngineeringUnits {
    // Acceleration
    MetersPerSecondPerSecond,

    // Area
    SquareMeters,
    SquareCentimeters,
    SquareFeet,
    SquareInches,

    // Currency
    Currency1,
    Currency2,
    Currency3,
    Currency4,
    Currency5,
    Currency6,
    Currency7,
    Currency8,
    Currency9,
    Currency10,

    // Electrical
    Milliamperes,
    Amperes,
    AmperesPerMeter,
    AmperesPerSquareMeter,
    AmpereSquareMeters,
    Decibels,
    DecibelsMillivolt,
    DecibelsVolt,
    Farads,
    Henrys,
    Ohms,
    OhmMeterSquaredPerMeter,
    OhmMeters,
    Milliohms,
    Kilohms,
    Megohms,
    Microsiemens,
    Millisiemens,
    Siemens,
    SiemensPerMeter,
    Teslas,
    Volts,
    Millivolts,
    Kilovolts,
    Megavolts,
    VoltAmperes,
    KilovoltAmperes,
    MegavoltAmperes,
    VoltAmperesReactive,
    KilovoltAmperesReactive,
    MegavoltAmperesReactive,
    VoltsPerDegreeKelvin,
    VoltsPerMeter,
    DegreesPhase,
    PowerFactor,
    Webers,

    // Energy
    AmpereSeconds,
    VoltAmpereHours,
    KilovoltAmpereHours,
    MegavoltAmpereHours,
    VoltAmpereHoursReactive,
    KilovoltAmpereHoursReactive,
    MegavoltAmpereHoursReactive,
    VoltSquareHours,
    AmpereSquareHours,
    Joules,
    Kilojoules,
    KilojoulesPerKilogram,
    Megajoules,
    WattHours,
    KilowattHours,
    MegawattHours,
    WattHoursReactive,
    KilowattHoursReactive,
    MegawattHoursReactive,
    Btus,
    KiloBtus,
    MegaBtus,
    Therms,
    TonHours,

    // Enthalpy
    JoulesPerKilogramDryAir,
    KilojoulesPerKilogramDryAir,
    MegajoulesPerKilogramDryAir,
    BtusPerPoundDryAir,
    BtusPerPound,

    // Entropy
    JoulesPerDegreeKelvin,
    KilojoulesPerDegreeKelvin,
    MegajoulesPerDegreeKelvin,
    JoulesPerKilogramDegreeKelvin,

    // Force
    Newton,

    // Frequency
    CyclesPerHour,
    CyclesPerMinute,
    Hertz,
    Kilohertz,
    Megahertz,
    PerHour,

    // Humidity
    GramsOfWaterPerKilogramDryAir,
    PercentRelativeHumidity,

    // Length
    Micrometers,
    Millimeters,
    Centimeters,
    Kilometers,
    Meters,
    Inches,
    Feet,

    // Light
    Candelas,
    CandelasPerSquareMeter,
    WattsPerSquareFoot,
    WattsPerSquareMeter,
    Lumens,
    Luxes,
    FootCandles,

    // Mass
    Milligrams,
    Grams,
    Kilograms,
    PoundsMass,
    Tons,

    // Mass Flow
    GramsPerSecond,
    GramsPerMinute,
    KilogramsPerSecond,
    KilogramsPerMinute,
    KilogramsPerHour,
    PoundsMassPerSecond,
    PoundsMassPerMinute,
    PoundsMassPerHour,
    TonsPerHour,

    // Power
    Milliwatts,
    Watts,
    Kilowatts,
    Megawatts,
    BtusPerHour,
    KiloBtusPerHour,
    JoulePerHours,
    Horsepower,
    TonsRefrigeration,

    // Pressure
    Pascals,
    Hectopascals,
    Kilopascals,
    Millibars,
    Bars,
    PoundsForcePerSquareInch,
    MillimetersOfWater,
    CentimetersOfWater,
    InchesOfWater,
    MillimetersOfMercury,
    CentimetersOfMercury,
    InchesOfMercury,

    // Temperature
    DegreesCelsius,
    DegreesKelvin,
    DegreesKelvinPerHour,
    DegreesKelvinPerMinute,
    DegreesFahrenheit,
    DegreeDaysCelsius,
    DegreeDaysFahrenheit,
    DeltaDegreesFahrenheit,
    DeltaDegreesKelvin,

    // Time
    Years,
    Months,
    Weeks,
    Days,
    Hours,
    Minutes,
    Seconds,
    HundredthsSeconds,
    Milliseconds,

    // Torque
    NewtonMeters,

    // Velocity
    MillimetersPerSecond,
    MillimetersPerMinute,
    MetersPerSecond,
    MetersPerMinute,
    MetersPerHour,
    KilometersPerHour,
    FeetPerSecond,
    FeetPerMinute,
    MilesPerHour,

    // Volume
    CubicFeet,
    CubicMeters,
    ImperialGallons,
    Milliliters,
    Liters,
    UsGallons,

    // Volumetric Flow
    CubicFeetPerSecond,
    CubicFeetPerMinute,
    MillionStandardCubicFeetPerMinute,
    CubicFeetPerHour,
    CubicFeetPerDay,
    StandardCubicFeetPerDay,
    MillionStandardCubicFeetPerDay,
    ThousandCubicFeetPerDay,
    ThousandStandardCubicFeetPerDay,
    PoundsMassPerDay,
    CubicMetersPerSecond,
    CubicMetersPerMinute,
    CubicMetersPerHour,
    CubicMetersPerDay,
    ImperialGallonsPerMinute,
    MillilitersPerSecond,
    LitersPerSecond,
    LitersPerMinute,
    LitersPerHour,
    UsGallonsPerMinute,
    UsGallonsPerHour,

    // Other
    DegreesAngular,
    DegreesCelsiusPerHour,
    DegreesCelsiusPerMinute,
    DegreesFahrenheitPerHour,
    DegreesFahrenheitPerMinute,
    JouleSeconds,
    KilogramsPerCubicMeter,
    KilowattHoursPerSquareMeter,
    KilowattHoursPerSquareFoot,
    WattHoursPerCubicMeter,
    JoulesPerCubicMeter,
    MegajoulesPerSquareMeter,
    MegajoulesPerSquareFoot,
    MolePercent,
    #[default]
    NoUnits,
    NewtonSeconds,
    NewtonsPerMeter,
    PartsPerMillion,
    PartsPerBillion,
    PascalSeconds,
    Percent,
    PercentObscurationPerFoot,
    PercentObscurationPerMeter,
    PercentPerSecond,
    PerMinute,
    PerSecond,
    PsiPerDegreeFahrenheit,
    Radians,
    RadiansPerSecond,
    RevolutionsPerMinute,
    SquareMetersPerNewton,
    WattsPerMeterPerDegreeKelvin,
    WattsPerSquareMeterDegreeKelvin,
    PerMille,
    GramsPerGram,
    KilogramsPerKilogram,
    GramsPerKilogram,
    MilligramsPerGram,
    MilligramsPerKilogram,
    GramsPerMilliliter,
    GramsPerLiter,
    MilligramsPerLiter,
    MicrogramsPerLiter,
    GramsPerCubicMeter,
    MilligramsPerCubicMeter,
    MicrogramsPerCubicMeter,
    NanogramsPerCubicMeter,
    GramsPerCubicCentimeter,
    Becquerels,
    Kilobecquerels,
    Megabecquerels,
    Gray,
    Milligray,
    Microgray,
    Sieverts,
    Millisieverts,
    Microsieverts,
    MicrosievertsPerHour,
    Millirems,
    MilliremsPerHour,
    DecibelsA,
    NephelometricTurbidityUnit,
    PH,
    GramsPerSquareMeter,
    MinutesPerDegreeKelvin,

    /// Vendor-specific or future engineering units
    /// Values 256-47807 and 50000-65535 may be used by others
    Other(u32),
}

impl EngineeringUnits {
    /// Convert from a u32 value to an EngineeringUnits variant
    ///
    /// For standard ASHRAE-defined units (0-255, 47808-49999), returns the
    /// corresponding variant. For vendor-specific values (256-47807, 50000-65535),
    /// returns `Other(value)`.
    pub fn from_u32(value: u32) -> Self {
        match value {
            166 => Self::MetersPerSecondPerSecond,
            0 => Self::SquareMeters,
            116 => Self::SquareCentimeters,
            1 => Self::SquareFeet,
            115 => Self::SquareInches,
            105 => Self::Currency1,
            106 => Self::Currency2,
            107 => Self::Currency3,
            108 => Self::Currency4,
            109 => Self::Currency5,
            110 => Self::Currency6,
            111 => Self::Currency7,
            112 => Self::Currency8,
            113 => Self::Currency9,
            114 => Self::Currency10,
            2 => Self::Milliamperes,
            3 => Self::Amperes,
            167 => Self::AmperesPerMeter,
            168 => Self::AmperesPerSquareMeter,
            169 => Self::AmpereSquareMeters,
            199 => Self::Decibels,
            200 => Self::DecibelsMillivolt,
            201 => Self::DecibelsVolt,
            170 => Self::Farads,
            171 => Self::Henrys,
            4 => Self::Ohms,
            237 => Self::OhmMeterSquaredPerMeter,
            172 => Self::OhmMeters,
            145 => Self::Milliohms,
            122 => Self::Kilohms,
            123 => Self::Megohms,
            190 => Self::Microsiemens,
            202 => Self::Millisiemens,
            173 => Self::Siemens,
            174 => Self::SiemensPerMeter,
            175 => Self::Teslas,
            5 => Self::Volts,
            124 => Self::Millivolts,
            6 => Self::Kilovolts,
            7 => Self::Megavolts,
            8 => Self::VoltAmperes,
            9 => Self::KilovoltAmperes,
            10 => Self::MegavoltAmperes,
            11 => Self::VoltAmperesReactive,
            12 => Self::KilovoltAmperesReactive,
            13 => Self::MegavoltAmperesReactive,
            176 => Self::VoltsPerDegreeKelvin,
            177 => Self::VoltsPerMeter,
            14 => Self::DegreesPhase,
            15 => Self::PowerFactor,
            178 => Self::Webers,
            238 => Self::AmpereSeconds,
            239 => Self::VoltAmpereHours,
            240 => Self::KilovoltAmpereHours,
            241 => Self::MegavoltAmpereHours,
            242 => Self::VoltAmpereHoursReactive,
            243 => Self::KilovoltAmpereHoursReactive,
            244 => Self::MegavoltAmpereHoursReactive,
            245 => Self::VoltSquareHours,
            246 => Self::AmpereSquareHours,
            16 => Self::Joules,
            17 => Self::Kilojoules,
            125 => Self::KilojoulesPerKilogram,
            126 => Self::Megajoules,
            18 => Self::WattHours,
            19 => Self::KilowattHours,
            146 => Self::MegawattHours,
            203 => Self::WattHoursReactive,
            204 => Self::KilowattHoursReactive,
            205 => Self::MegawattHoursReactive,
            20 => Self::Btus,
            147 => Self::KiloBtus,
            148 => Self::MegaBtus,
            21 => Self::Therms,
            22 => Self::TonHours,
            23 => Self::JoulesPerKilogramDryAir,
            149 => Self::KilojoulesPerKilogramDryAir,
            150 => Self::MegajoulesPerKilogramDryAir,
            24 => Self::BtusPerPoundDryAir,
            117 => Self::BtusPerPound,
            127 => Self::JoulesPerDegreeKelvin,
            151 => Self::KilojoulesPerDegreeKelvin,
            152 => Self::MegajoulesPerDegreeKelvin,
            128 => Self::JoulesPerKilogramDegreeKelvin,
            153 => Self::Newton,
            25 => Self::CyclesPerHour,
            26 => Self::CyclesPerMinute,
            27 => Self::Hertz,
            129 => Self::Kilohertz,
            130 => Self::Megahertz,
            131 => Self::PerHour,
            28 => Self::GramsOfWaterPerKilogramDryAir,
            29 => Self::PercentRelativeHumidity,
            194 => Self::Micrometers,
            30 => Self::Millimeters,
            118 => Self::Centimeters,
            193 => Self::Kilometers,
            31 => Self::Meters,
            32 => Self::Inches,
            33 => Self::Feet,
            179 => Self::Candelas,
            180 => Self::CandelasPerSquareMeter,
            34 => Self::WattsPerSquareFoot,
            35 => Self::WattsPerSquareMeter,
            36 => Self::Lumens,
            37 => Self::Luxes,
            38 => Self::FootCandles,
            196 => Self::Milligrams,
            195 => Self::Grams,
            39 => Self::Kilograms,
            40 => Self::PoundsMass,
            41 => Self::Tons,
            154 => Self::GramsPerSecond,
            155 => Self::GramsPerMinute,
            42 => Self::KilogramsPerSecond,
            43 => Self::KilogramsPerMinute,
            44 => Self::KilogramsPerHour,
            119 => Self::PoundsMassPerSecond,
            45 => Self::PoundsMassPerMinute,
            46 => Self::PoundsMassPerHour,
            156 => Self::TonsPerHour,
            132 => Self::Milliwatts,
            47 => Self::Watts,
            48 => Self::Kilowatts,
            49 => Self::Megawatts,
            50 => Self::BtusPerHour,
            157 => Self::KiloBtusPerHour,
            247 => Self::JoulePerHours,
            51 => Self::Horsepower,
            52 => Self::TonsRefrigeration,
            53 => Self::Pascals,
            133 => Self::Hectopascals,
            54 => Self::Kilopascals,
            134 => Self::Millibars,
            55 => Self::Bars,
            56 => Self::PoundsForcePerSquareInch,
            206 => Self::MillimetersOfWater,
            57 => Self::CentimetersOfWater,
            58 => Self::InchesOfWater,
            59 => Self::MillimetersOfMercury,
            60 => Self::CentimetersOfMercury,
            61 => Self::InchesOfMercury,
            62 => Self::DegreesCelsius,
            63 => Self::DegreesKelvin,
            181 => Self::DegreesKelvinPerHour,
            182 => Self::DegreesKelvinPerMinute,
            64 => Self::DegreesFahrenheit,
            65 => Self::DegreeDaysCelsius,
            66 => Self::DegreeDaysFahrenheit,
            120 => Self::DeltaDegreesFahrenheit,
            121 => Self::DeltaDegreesKelvin,
            67 => Self::Years,
            68 => Self::Months,
            69 => Self::Weeks,
            70 => Self::Days,
            71 => Self::Hours,
            72 => Self::Minutes,
            73 => Self::Seconds,
            158 => Self::HundredthsSeconds,
            159 => Self::Milliseconds,
            160 => Self::NewtonMeters,
            161 => Self::MillimetersPerSecond,
            162 => Self::MillimetersPerMinute,
            74 => Self::MetersPerSecond,
            163 => Self::MetersPerMinute,
            164 => Self::MetersPerHour,
            75 => Self::KilometersPerHour,
            76 => Self::FeetPerSecond,
            77 => Self::FeetPerMinute,
            78 => Self::MilesPerHour,
            79 => Self::CubicFeet,
            80 => Self::CubicMeters,
            81 => Self::ImperialGallons,
            197 => Self::Milliliters,
            82 => Self::Liters,
            83 => Self::UsGallons,
            142 => Self::CubicFeetPerSecond,
            84 => Self::CubicFeetPerMinute,
            254 => Self::MillionStandardCubicFeetPerMinute,
            191 => Self::CubicFeetPerHour,
            248 => Self::CubicFeetPerDay,
            47808 => Self::StandardCubicFeetPerDay,
            47809 => Self::MillionStandardCubicFeetPerDay,
            47810 => Self::ThousandCubicFeetPerDay,
            47811 => Self::ThousandStandardCubicFeetPerDay,
            47812 => Self::PoundsMassPerDay,
            85 => Self::CubicMetersPerSecond,
            165 => Self::CubicMetersPerMinute,
            135 => Self::CubicMetersPerHour,
            249 => Self::CubicMetersPerDay,
            86 => Self::ImperialGallonsPerMinute,
            198 => Self::MillilitersPerSecond,
            87 => Self::LitersPerSecond,
            88 => Self::LitersPerMinute,
            136 => Self::LitersPerHour,
            89 => Self::UsGallonsPerMinute,
            192 => Self::UsGallonsPerHour,
            90 => Self::DegreesAngular,
            91 => Self::DegreesCelsiusPerHour,
            92 => Self::DegreesCelsiusPerMinute,
            93 => Self::DegreesFahrenheitPerHour,
            94 => Self::DegreesFahrenheitPerMinute,
            183 => Self::JouleSeconds,
            186 => Self::KilogramsPerCubicMeter,
            137 => Self::KilowattHoursPerSquareMeter,
            138 => Self::KilowattHoursPerSquareFoot,
            250 => Self::WattHoursPerCubicMeter,
            251 => Self::JoulesPerCubicMeter,
            139 => Self::MegajoulesPerSquareMeter,
            140 => Self::MegajoulesPerSquareFoot,
            252 => Self::MolePercent,
            95 => Self::NoUnits,
            187 => Self::NewtonSeconds,
            188 => Self::NewtonsPerMeter,
            96 => Self::PartsPerMillion,
            97 => Self::PartsPerBillion,
            253 => Self::PascalSeconds,
            98 => Self::Percent,
            143 => Self::PercentObscurationPerFoot,
            144 => Self::PercentObscurationPerMeter,
            99 => Self::PercentPerSecond,
            100 => Self::PerMinute,
            101 => Self::PerSecond,
            102 => Self::PsiPerDegreeFahrenheit,
            103 => Self::Radians,
            184 => Self::RadiansPerSecond,
            104 => Self::RevolutionsPerMinute,
            185 => Self::SquareMetersPerNewton,
            189 => Self::WattsPerMeterPerDegreeKelvin,
            141 => Self::WattsPerSquareMeterDegreeKelvin,
            207 => Self::PerMille,
            208 => Self::GramsPerGram,
            209 => Self::KilogramsPerKilogram,
            210 => Self::GramsPerKilogram,
            211 => Self::MilligramsPerGram,
            212 => Self::MilligramsPerKilogram,
            213 => Self::GramsPerMilliliter,
            214 => Self::GramsPerLiter,
            215 => Self::MilligramsPerLiter,
            216 => Self::MicrogramsPerLiter,
            217 => Self::GramsPerCubicMeter,
            218 => Self::MilligramsPerCubicMeter,
            219 => Self::MicrogramsPerCubicMeter,
            220 => Self::NanogramsPerCubicMeter,
            221 => Self::GramsPerCubicCentimeter,
            222 => Self::Becquerels,
            223 => Self::Kilobecquerels,
            224 => Self::Megabecquerels,
            225 => Self::Gray,
            226 => Self::Milligray,
            227 => Self::Microgray,
            228 => Self::Sieverts,
            229 => Self::Millisieverts,
            230 => Self::Microsieverts,
            231 => Self::MicrosievertsPerHour,
            47814 => Self::Millirems,
            47815 => Self::MilliremsPerHour,
            232 => Self::DecibelsA,
            233 => Self::NephelometricTurbidityUnit,
            234 => Self::PH,
            235 => Self::GramsPerSquareMeter,
            236 => Self::MinutesPerDegreeKelvin,
            // Vendor-specific or future units
            _ => Self::Other(value),
        }
    }

    /// Convert to a u32 value
    pub fn to_u32(&self) -> u32 {
        match self {
            // Acceleration
            Self::MetersPerSecondPerSecond => 166,

            // Area
            Self::SquareMeters => 0,
            Self::SquareCentimeters => 116,
            Self::SquareFeet => 1,
            Self::SquareInches => 115,

            // Currency
            Self::Currency1 => 105,
            Self::Currency2 => 106,
            Self::Currency3 => 107,
            Self::Currency4 => 108,
            Self::Currency5 => 109,
            Self::Currency6 => 110,
            Self::Currency7 => 111,
            Self::Currency8 => 112,
            Self::Currency9 => 113,
            Self::Currency10 => 114,

            // Electrical
            Self::Milliamperes => 2,
            Self::Amperes => 3,
            Self::AmperesPerMeter => 167,
            Self::AmperesPerSquareMeter => 168,
            Self::AmpereSquareMeters => 169,
            Self::Decibels => 199,
            Self::DecibelsMillivolt => 200,
            Self::DecibelsVolt => 201,
            Self::Farads => 170,
            Self::Henrys => 171,
            Self::Ohms => 4,
            Self::OhmMeterSquaredPerMeter => 237,
            Self::OhmMeters => 172,
            Self::Milliohms => 145,
            Self::Kilohms => 122,
            Self::Megohms => 123,
            Self::Microsiemens => 190,
            Self::Millisiemens => 202,
            Self::Siemens => 173,
            Self::SiemensPerMeter => 174,
            Self::Teslas => 175,
            Self::Volts => 5,
            Self::Millivolts => 124,
            Self::Kilovolts => 6,
            Self::Megavolts => 7,
            Self::VoltAmperes => 8,
            Self::KilovoltAmperes => 9,
            Self::MegavoltAmperes => 10,
            Self::VoltAmperesReactive => 11,
            Self::KilovoltAmperesReactive => 12,
            Self::MegavoltAmperesReactive => 13,
            Self::VoltsPerDegreeKelvin => 176,
            Self::VoltsPerMeter => 177,
            Self::DegreesPhase => 14,
            Self::PowerFactor => 15,
            Self::Webers => 178,

            // Energy
            Self::AmpereSeconds => 238,
            Self::VoltAmpereHours => 239,
            Self::KilovoltAmpereHours => 240,
            Self::MegavoltAmpereHours => 241,
            Self::VoltAmpereHoursReactive => 242,
            Self::KilovoltAmpereHoursReactive => 243,
            Self::MegavoltAmpereHoursReactive => 244,
            Self::VoltSquareHours => 245,
            Self::AmpereSquareHours => 246,
            Self::Joules => 16,
            Self::Kilojoules => 17,
            Self::KilojoulesPerKilogram => 125,
            Self::Megajoules => 126,
            Self::WattHours => 18,
            Self::KilowattHours => 19,
            Self::MegawattHours => 146,
            Self::WattHoursReactive => 203,
            Self::KilowattHoursReactive => 204,
            Self::MegawattHoursReactive => 205,
            Self::Btus => 20,
            Self::KiloBtus => 147,
            Self::MegaBtus => 148,
            Self::Therms => 21,
            Self::TonHours => 22,

            // Enthalpy
            Self::JoulesPerKilogramDryAir => 23,
            Self::KilojoulesPerKilogramDryAir => 149,
            Self::MegajoulesPerKilogramDryAir => 150,
            Self::BtusPerPoundDryAir => 24,
            Self::BtusPerPound => 117,

            // Entropy
            Self::JoulesPerDegreeKelvin => 127,
            Self::KilojoulesPerDegreeKelvin => 151,
            Self::MegajoulesPerDegreeKelvin => 152,
            Self::JoulesPerKilogramDegreeKelvin => 128,

            // Force
            Self::Newton => 153,

            // Frequency
            Self::CyclesPerHour => 25,
            Self::CyclesPerMinute => 26,
            Self::Hertz => 27,
            Self::Kilohertz => 129,
            Self::Megahertz => 130,
            Self::PerHour => 131,

            // Humidity
            Self::GramsOfWaterPerKilogramDryAir => 28,
            Self::PercentRelativeHumidity => 29,

            // Length
            Self::Micrometers => 194,
            Self::Millimeters => 30,
            Self::Centimeters => 118,
            Self::Kilometers => 193,
            Self::Meters => 31,
            Self::Inches => 32,
            Self::Feet => 33,

            // Light
            Self::Candelas => 179,
            Self::CandelasPerSquareMeter => 180,
            Self::WattsPerSquareFoot => 34,
            Self::WattsPerSquareMeter => 35,
            Self::Lumens => 36,
            Self::Luxes => 37,
            Self::FootCandles => 38,

            // Mass
            Self::Milligrams => 196,
            Self::Grams => 195,
            Self::Kilograms => 39,
            Self::PoundsMass => 40,
            Self::Tons => 41,

            // Mass Flow
            Self::GramsPerSecond => 154,
            Self::GramsPerMinute => 155,
            Self::KilogramsPerSecond => 42,
            Self::KilogramsPerMinute => 43,
            Self::KilogramsPerHour => 44,
            Self::PoundsMassPerSecond => 119,
            Self::PoundsMassPerMinute => 45,
            Self::PoundsMassPerHour => 46,
            Self::TonsPerHour => 156,

            // Power
            Self::Milliwatts => 132,
            Self::Watts => 47,
            Self::Kilowatts => 48,
            Self::Megawatts => 49,
            Self::BtusPerHour => 50,
            Self::KiloBtusPerHour => 157,
            Self::JoulePerHours => 247,
            Self::Horsepower => 51,
            Self::TonsRefrigeration => 52,

            // Pressure
            Self::Pascals => 53,
            Self::Hectopascals => 133,
            Self::Kilopascals => 54,
            Self::Millibars => 134,
            Self::Bars => 55,
            Self::PoundsForcePerSquareInch => 56,
            Self::MillimetersOfWater => 206,
            Self::CentimetersOfWater => 57,
            Self::InchesOfWater => 58,
            Self::MillimetersOfMercury => 59,
            Self::CentimetersOfMercury => 60,
            Self::InchesOfMercury => 61,

            // Temperature
            Self::DegreesCelsius => 62,
            Self::DegreesKelvin => 63,
            Self::DegreesKelvinPerHour => 181,
            Self::DegreesKelvinPerMinute => 182,
            Self::DegreesFahrenheit => 64,
            Self::DegreeDaysCelsius => 65,
            Self::DegreeDaysFahrenheit => 66,
            Self::DeltaDegreesFahrenheit => 120,
            Self::DeltaDegreesKelvin => 121,

            // Time
            Self::Years => 67,
            Self::Months => 68,
            Self::Weeks => 69,
            Self::Days => 70,
            Self::Hours => 71,
            Self::Minutes => 72,
            Self::Seconds => 73,
            Self::HundredthsSeconds => 158,
            Self::Milliseconds => 159,

            // Torque
            Self::NewtonMeters => 160,

            // Velocity
            Self::MillimetersPerSecond => 161,
            Self::MillimetersPerMinute => 162,
            Self::MetersPerSecond => 74,
            Self::MetersPerMinute => 163,
            Self::MetersPerHour => 164,
            Self::KilometersPerHour => 75,
            Self::FeetPerSecond => 76,
            Self::FeetPerMinute => 77,
            Self::MilesPerHour => 78,

            // Volume
            Self::CubicFeet => 79,
            Self::CubicMeters => 80,
            Self::ImperialGallons => 81,
            Self::Milliliters => 197,
            Self::Liters => 82,
            Self::UsGallons => 83,

            // Volumetric Flow
            Self::CubicFeetPerSecond => 142,
            Self::CubicFeetPerMinute => 84,
            Self::MillionStandardCubicFeetPerMinute => 254,
            Self::CubicFeetPerHour => 191,
            Self::CubicFeetPerDay => 248,
            Self::StandardCubicFeetPerDay => 47808,
            Self::MillionStandardCubicFeetPerDay => 47809,
            Self::ThousandCubicFeetPerDay => 47810,
            Self::ThousandStandardCubicFeetPerDay => 47811,
            Self::PoundsMassPerDay => 47812,
            Self::CubicMetersPerSecond => 85,
            Self::CubicMetersPerMinute => 165,
            Self::CubicMetersPerHour => 135,
            Self::CubicMetersPerDay => 249,
            Self::ImperialGallonsPerMinute => 86,
            Self::MillilitersPerSecond => 198,
            Self::LitersPerSecond => 87,
            Self::LitersPerMinute => 88,
            Self::LitersPerHour => 136,
            Self::UsGallonsPerMinute => 89,
            Self::UsGallonsPerHour => 192,

            // Other
            Self::DegreesAngular => 90,
            Self::DegreesCelsiusPerHour => 91,
            Self::DegreesCelsiusPerMinute => 92,
            Self::DegreesFahrenheitPerHour => 93,
            Self::DegreesFahrenheitPerMinute => 94,
            Self::JouleSeconds => 183,
            Self::KilogramsPerCubicMeter => 186,
            Self::KilowattHoursPerSquareMeter => 137,
            Self::KilowattHoursPerSquareFoot => 138,
            Self::WattHoursPerCubicMeter => 250,
            Self::JoulesPerCubicMeter => 251,
            Self::MegajoulesPerSquareMeter => 139,
            Self::MegajoulesPerSquareFoot => 140,
            Self::MolePercent => 252,
            Self::NoUnits => 95,
            Self::NewtonSeconds => 187,
            Self::NewtonsPerMeter => 188,
            Self::PartsPerMillion => 96,
            Self::PartsPerBillion => 97,
            Self::PascalSeconds => 253,
            Self::Percent => 98,
            Self::PercentObscurationPerFoot => 143,
            Self::PercentObscurationPerMeter => 144,
            Self::PercentPerSecond => 99,
            Self::PerMinute => 100,
            Self::PerSecond => 101,
            Self::PsiPerDegreeFahrenheit => 102,
            Self::Radians => 103,
            Self::RadiansPerSecond => 184,
            Self::RevolutionsPerMinute => 104,
            Self::SquareMetersPerNewton => 185,
            Self::WattsPerMeterPerDegreeKelvin => 189,
            Self::WattsPerSquareMeterDegreeKelvin => 141,
            Self::PerMille => 207,
            Self::GramsPerGram => 208,
            Self::KilogramsPerKilogram => 209,
            Self::GramsPerKilogram => 210,
            Self::MilligramsPerGram => 211,
            Self::MilligramsPerKilogram => 212,
            Self::GramsPerMilliliter => 213,
            Self::GramsPerLiter => 214,
            Self::MilligramsPerLiter => 215,
            Self::MicrogramsPerLiter => 216,
            Self::GramsPerCubicMeter => 217,
            Self::MilligramsPerCubicMeter => 218,
            Self::MicrogramsPerCubicMeter => 219,
            Self::NanogramsPerCubicMeter => 220,
            Self::GramsPerCubicCentimeter => 221,
            Self::Becquerels => 222,
            Self::Kilobecquerels => 223,
            Self::Megabecquerels => 224,
            Self::Gray => 225,
            Self::Milligray => 226,
            Self::Microgray => 227,
            Self::Sieverts => 228,
            Self::Millisieverts => 229,
            Self::Microsieverts => 230,
            Self::MicrosievertsPerHour => 231,
            Self::Millirems => 47814,
            Self::MilliremsPerHour => 47815,
            Self::DecibelsA => 232,
            Self::NephelometricTurbidityUnit => 233,
            Self::PH => 234,
            Self::GramsPerSquareMeter => 235,
            Self::MinutesPerDegreeKelvin => 236,

            // Vendor-specific
            Self::Other(value) => *value,
        }
    }

    /// Get the category of this unit
    pub fn category(&self) -> &'static str {
        match self.to_u32() {
            166 => "Acceleration",
            0..=1 | 115..=116 => "Area",
            105..=114 => "Currency",
            2..=15 | 122..=124 | 145 | 167..=178 | 199..=202 | 237 => "Electrical",
            16..=22 | 125..=126 | 146..=148 | 203..=205 | 238..=246 => "Energy",
            23..=24 | 117 => "Enthalpy",
            127..=128 | 151..=152 => "Entropy",
            153 => "Force",
            25..=27 | 129..=131 => "Frequency",
            28..=29 => "Humidity",
            30..=33 | 118 | 193..=194 => "Length",
            34..=38 | 179..=180 => "Light",
            39..=41 | 195..=196 => "Mass",
            42..=46 | 119 | 154..=156 => "Mass Flow",
            47..=52 | 132 | 157 => "Power",
            53..=61 | 133..=134 | 206 => "Pressure",
            62..=66 | 120..=121 | 181..=182 => "Temperature",
            67..=73 | 158..=159 => "Time",
            160 => "Torque",
            74..=78 | 161..=164 => "Velocity",
            79..=83 | 197 => "Volume",
            84..=89 | 135..=136 | 142 | 165 | 191..=192 | 198 | 248..=254 | 47808..=47812 => {
                "Volumetric Flow"
            }
            _ => "Other",
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_from_u32() {
        // Test standard ASHRAE units
        assert_eq!(EngineeringUnits::from_u32(95), EngineeringUnits::NoUnits);
        assert_eq!(
            EngineeringUnits::from_u32(62),
            EngineeringUnits::DegreesCelsius
        );
        assert_eq!(
            EngineeringUnits::from_u32(64),
            EngineeringUnits::DegreesFahrenheit
        );

        // Test vendor-specific units (256-47807)
        assert_eq!(
            EngineeringUnits::from_u32(1000),
            EngineeringUnits::Other(1000)
        );

        // Test vendor-specific units (50000-65535)
        assert_eq!(
            EngineeringUnits::from_u32(50000),
            EngineeringUnits::Other(50000)
        );
    }

    #[test]
    fn test_to_u32() {
        assert_eq!(EngineeringUnits::NoUnits.to_u32(), 95);
        assert_eq!(EngineeringUnits::DegreesCelsius.to_u32(), 62);
        assert_eq!(EngineeringUnits::Other(1000).to_u32(), 1000);
    }

    #[test]
    fn test_roundtrip() {
        // Standard units should roundtrip
        let celsius = EngineeringUnits::DegreesCelsius;
        assert_eq!(EngineeringUnits::from_u32(celsius.to_u32()), celsius);

        // Vendor-specific units should roundtrip
        let custom = EngineeringUnits::Other(12345);
        assert_eq!(EngineeringUnits::from_u32(custom.to_u32()), custom);
    }

    #[test]
    fn test_category() {
        assert_eq!(EngineeringUnits::DegreesCelsius.category(), "Temperature");
        assert_eq!(EngineeringUnits::Watts.category(), "Power");
        assert_eq!(EngineeringUnits::Meters.category(), "Length");
        assert_eq!(EngineeringUnits::Other(12345).category(), "Other");
    }

    #[test]
    fn test_default() {
        assert_eq!(EngineeringUnits::default(), EngineeringUnits::NoUnits);
    }
}
