//! BACnet Engineering Units
//!
//! This module defines the complete set of engineering units as specified in
//! ISO 16484-5:2017 page 791 (ASHRAE Standard 135-2020).
//!
//! The enum includes all standard BACnet engineering units with their exact
//! numeric values for protocol compatibility.

/// BACnet Engineering Units enumeration
///
/// Represents all engineering units defined in the BACnet standard.
/// Values 0-255 and 47808-49999 are reserved for definition by ASHRAE.
/// Values 256-47807 and 50000-65535 may be used by others.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
#[repr(u32)]
pub enum EngineeringUnits {
    // Acceleration
    MetersPerSecondPerSecond = 166,

    // Area
    SquareMeters = 0,
    SquareCentimeters = 116,
    SquareFeet = 1,
    SquareInches = 115,

    // Currency
    Currency1 = 105,
    Currency2 = 106,
    Currency3 = 107,
    Currency4 = 108,
    Currency5 = 109,
    Currency6 = 110,
    Currency7 = 111,
    Currency8 = 112,
    Currency9 = 113,
    Currency10 = 114,

    // Electrical
    Milliamperes = 2,
    Amperes = 3,
    AmperesPerMeter = 167,
    AmperesPerSquareMeter = 168,
    AmpereSquareMeters = 169,
    Decibels = 199,
    DecibelsMillivolt = 200,
    DecibelsVolt = 201,
    Farads = 170,
    Henrys = 171,
    Ohms = 4,
    OhmMeterSquaredPerMeter = 237,
    OhmMeters = 172,
    Milliohms = 145,
    Kilohms = 122,
    Megohms = 123,
    Microsiemens = 190,
    Millisiemens = 202,
    Siemens = 173,
    SiemensPerMeter = 174,
    Teslas = 175,
    Volts = 5,
    Millivolts = 124,
    Kilovolts = 6,
    Megavolts = 7,
    VoltAmperes = 8,
    KilovoltAmperes = 9,
    MegavoltAmperes = 10,
    VoltAmperesReactive = 11,
    KilovoltAmperesReactive = 12,
    MegavoltAmperesReactive = 13,
    VoltsPerDegreeKelvin = 176,
    VoltsPerMeter = 177,
    DegreesPhase = 14,
    PowerFactor = 15,
    Webers = 178,

    // Energy
    AmpereSeconds = 238,
    VoltAmpereHours = 239,
    KilovoltAmpereHours = 240,
    MegavoltAmpereHours = 241,
    VoltAmpereHoursReactive = 242,
    KilovoltAmpereHoursReactive = 243,
    MegavoltAmpereHoursReactive = 244,
    VoltSquareHours = 245,
    AmpereSquareHours = 246,
    Joules = 16,
    Kilojoules = 17,
    KilojoulesPerKilogram = 125,
    Megajoules = 126,
    WattHours = 18,
    KilowattHours = 19,
    MegawattHours = 146,
    WattHoursReactive = 203,
    KilowattHoursReactive = 204,
    MegawattHoursReactive = 205,
    Btus = 20,
    KiloBtus = 147,
    MegaBtus = 148,
    Therms = 21,
    TonHours = 22,

    // Enthalpy
    JoulesPerKilogramDryAir = 23,
    KilojoulesPerKilogramDryAir = 149,
    MegajoulesPerKilogramDryAir = 150,
    BtusPerPoundDryAir = 24,
    BtusPerPound = 117,

    // Entropy
    JoulesPerDegreeKelvin = 127,
    KilojoulesPerDegreeKelvin = 151,
    MegajoulesPerDegreeKelvin = 152,
    JoulesPerKilogramDegreeKelvin = 128,

    // Force
    Newton = 153,

    // Frequency
    CyclesPerHour = 25,
    CyclesPerMinute = 26,
    Hertz = 27,
    Kilohertz = 129,
    Megahertz = 130,
    PerHour = 131,

    // Humidity
    GramsOfWaterPerKilogramDryAir = 28,
    PercentRelativeHumidity = 29,

    // Length
    Micrometers = 194,
    Millimeters = 30,
    Centimeters = 118,
    Kilometers = 193,
    Meters = 31,
    Inches = 32,
    Feet = 33,

    // Light
    Candelas = 179,
    CandelasPerSquareMeter = 180,
    WattsPerSquareFoot = 34,
    WattsPerSquareMeter = 35,
    Lumens = 36,
    Luxes = 37,
    FootCandles = 38,

    // Mass
    Milligrams = 196,
    Grams = 195,
    Kilograms = 39,
    PoundsMass = 40,
    Tons = 41,

    // Mass Flow
    GramsPerSecond = 154,
    GramsPerMinute = 155,
    KilogramsPerSecond = 42,
    KilogramsPerMinute = 43,
    KilogramsPerHour = 44,
    PoundsMassPerSecond = 119,
    PoundsMassPerMinute = 45,
    PoundsMassPerHour = 46,
    TonsPerHour = 156,

    // Power
    Milliwatts = 132,
    Watts = 47,
    Kilowatts = 48,
    Megawatts = 49,
    BtusPerHour = 50,
    KiloBtusPerHour = 157,
    JoulePerHours = 247,
    Horsepower = 51,
    TonsRefrigeration = 52,

    // Pressure
    Pascals = 53,
    Hectopascals = 133,
    Kilopascals = 54,
    Millibars = 134,
    Bars = 55,
    PoundsForcePerSquareInch = 56,
    MillimetersOfWater = 206,
    CentimetersOfWater = 57,
    InchesOfWater = 58,
    MillimetersOfMercury = 59,
    CentimetersOfMercury = 60,
    InchesOfMercury = 61,

    // Temperature
    DegreesCelsius = 62,
    DegreesKelvin = 63,
    DegreesKelvinPerHour = 181,
    DegreesKelvinPerMinute = 182,
    DegreesFahrenheit = 64,
    DegreeDaysCelsius = 65,
    DegreeDaysFahrenheit = 66,
    DeltaDegreesFahrenheit = 120,
    DeltaDegreesKelvin = 121,

    // Time
    Years = 67,
    Months = 68,
    Weeks = 69,
    Days = 70,
    Hours = 71,
    Minutes = 72,
    Seconds = 73,
    HundredthsSeconds = 158,
    Milliseconds = 159,

    // Torque
    NewtonMeters = 160,

    // Velocity
    MillimetersPerSecond = 161,
    MillimetersPerMinute = 162,
    MetersPerSecond = 74,
    MetersPerMinute = 163,
    MetersPerHour = 164,
    KilometersPerHour = 75,
    FeetPerSecond = 76,
    FeetPerMinute = 77,
    MilesPerHour = 78,

    // Volume
    CubicFeet = 79,
    CubicMeters = 80,
    ImperialGallons = 81,
    Milliliters = 197,
    Liters = 82,
    UsGallons = 83,

    // Volumetric Flow
    CubicFeetPerSecond = 142,
    CubicFeetPerMinute = 84,
    MillionStandardCubicFeetPerMinute = 254,
    CubicFeetPerHour = 191,
    CubicFeetPerDay = 248,
    StandardCubicFeetPerDay = 47808,
    MillionStandardCubicFeetPerDay = 47809,
    ThousandCubicFeetPerDay = 47810,
    ThousandStandardCubicFeetPerDay = 47811,
    PoundsMassPerDay = 47812,
    CubicMetersPerSecond = 85,
    CubicMetersPerMinute = 165,
    CubicMetersPerHour = 135,
    CubicMetersPerDay = 249,
    ImperialGallonsPerMinute = 86,
    MillilitersPerSecond = 198,
    LitersPerSecond = 87,
    LitersPerMinute = 88,
    LitersPerHour = 136,
    UsGallonsPerMinute = 89,
    UsGallonsPerHour = 192,

    // Other
    DegreesAngular = 90,
    DegreesCelsiusPerHour = 91,
    DegreesCelsiusPerMinute = 92,
    DegreesFahrenheitPerHour = 93,
    DegreesFahrenheitPerMinute = 94,
    JouleSeconds = 183,
    KilogramsPerCubicMeter = 186,
    KilowattHoursPerSquareMeter = 137,
    KilowattHoursPerSquareFoot = 138,
    WattHoursPerCubicMeter = 250,
    JoulesPerCubicMeter = 251,
    MegajoulesPerSquareMeter = 139,
    MegajoulesPerSquareFoot = 140,
    MolePercent = 252,
    NoUnits = 95,
    NewtonSeconds = 187,
    NewtonsPerMeter = 188,
    PartsPerMillion = 96,
    PartsPerBillion = 97,
    PascalSeconds = 253,
    Percent = 98,
    PercentObscurationPerFoot = 143,
    PercentObscurationPerMeter = 144,
    PercentPerSecond = 99,
    PerMinute = 100,
    PerSecond = 101,
    PsiPerDegreeFahrenheit = 102,
    Radians = 103,
    RadiansPerSecond = 184,
    RevolutionsPerMinute = 104,
    SquareMetersPerNewton = 185,
    WattsPerMeterPerDegreeKelvin = 189,
    WattsPerSquareMeterDegreeKelvin = 141,
    PerMille = 207,
    GramsPerGram = 208,
    KilogramsPerKilogram = 209,
    GramsPerKilogram = 210,
    MilligramsPerGram = 211,
    MilligramsPerKilogram = 212,
    GramsPerMilliliter = 213,
    GramsPerLiter = 214,
    MilligramsPerLiter = 215,
    MicrogramsPerLiter = 216,
    GramsPerCubicMeter = 217,
    MilligramsPerCubicMeter = 218,
    MicrogramsPerCubicMeter = 219,
    NanogramsPerCubicMeter = 220,
    GramsPerCubicCentimeter = 221,
    Becquerels = 222,
    Kilobecquerels = 223,
    Megabecquerels = 224,
    Gray = 225,
    Milligray = 226,
    Microgray = 227,
    Sieverts = 228,
    Millisieverts = 229,
    Microsieverts = 230,
    MicrosievertsPerHour = 231,
    Millirems = 47814,
    MilliremsPerHour = 47815,
    DecibelsA = 232,
    NephelometricTurbidityUnit = 233,
    PH = 234,
    GramsPerSquareMeter = 235,
    MinutesPerDegreeKelvin = 236,
}

impl EngineeringUnits {
    /// Convert from a u32 value to an EngineeringUnits variant
    ///
    /// Returns `None` if the value doesn't correspond to a valid unit.
    pub fn from_u32(value: u32) -> Option<Self> {
        match value {
            166 => Some(Self::MetersPerSecondPerSecond),
            0 => Some(Self::SquareMeters),
            116 => Some(Self::SquareCentimeters),
            1 => Some(Self::SquareFeet),
            115 => Some(Self::SquareInches),
            105 => Some(Self::Currency1),
            106 => Some(Self::Currency2),
            107 => Some(Self::Currency3),
            108 => Some(Self::Currency4),
            109 => Some(Self::Currency5),
            110 => Some(Self::Currency6),
            111 => Some(Self::Currency7),
            112 => Some(Self::Currency8),
            113 => Some(Self::Currency9),
            114 => Some(Self::Currency10),
            2 => Some(Self::Milliamperes),
            3 => Some(Self::Amperes),
            167 => Some(Self::AmperesPerMeter),
            168 => Some(Self::AmperesPerSquareMeter),
            169 => Some(Self::AmpereSquareMeters),
            199 => Some(Self::Decibels),
            200 => Some(Self::DecibelsMillivolt),
            201 => Some(Self::DecibelsVolt),
            170 => Some(Self::Farads),
            171 => Some(Self::Henrys),
            4 => Some(Self::Ohms),
            237 => Some(Self::OhmMeterSquaredPerMeter),
            172 => Some(Self::OhmMeters),
            145 => Some(Self::Milliohms),
            122 => Some(Self::Kilohms),
            123 => Some(Self::Megohms),
            190 => Some(Self::Microsiemens),
            202 => Some(Self::Millisiemens),
            173 => Some(Self::Siemens),
            174 => Some(Self::SiemensPerMeter),
            175 => Some(Self::Teslas),
            5 => Some(Self::Volts),
            124 => Some(Self::Millivolts),
            6 => Some(Self::Kilovolts),
            7 => Some(Self::Megavolts),
            8 => Some(Self::VoltAmperes),
            9 => Some(Self::KilovoltAmperes),
            10 => Some(Self::MegavoltAmperes),
            11 => Some(Self::VoltAmperesReactive),
            12 => Some(Self::KilovoltAmperesReactive),
            13 => Some(Self::MegavoltAmperesReactive),
            176 => Some(Self::VoltsPerDegreeKelvin),
            177 => Some(Self::VoltsPerMeter),
            14 => Some(Self::DegreesPhase),
            15 => Some(Self::PowerFactor),
            178 => Some(Self::Webers),
            238 => Some(Self::AmpereSeconds),
            239 => Some(Self::VoltAmpereHours),
            240 => Some(Self::KilovoltAmpereHours),
            241 => Some(Self::MegavoltAmpereHours),
            242 => Some(Self::VoltAmpereHoursReactive),
            243 => Some(Self::KilovoltAmpereHoursReactive),
            244 => Some(Self::MegavoltAmpereHoursReactive),
            245 => Some(Self::VoltSquareHours),
            246 => Some(Self::AmpereSquareHours),
            16 => Some(Self::Joules),
            17 => Some(Self::Kilojoules),
            125 => Some(Self::KilojoulesPerKilogram),
            126 => Some(Self::Megajoules),
            18 => Some(Self::WattHours),
            19 => Some(Self::KilowattHours),
            146 => Some(Self::MegawattHours),
            203 => Some(Self::WattHoursReactive),
            204 => Some(Self::KilowattHoursReactive),
            205 => Some(Self::MegawattHoursReactive),
            20 => Some(Self::Btus),
            147 => Some(Self::KiloBtus),
            148 => Some(Self::MegaBtus),
            21 => Some(Self::Therms),
            22 => Some(Self::TonHours),
            23 => Some(Self::JoulesPerKilogramDryAir),
            149 => Some(Self::KilojoulesPerKilogramDryAir),
            150 => Some(Self::MegajoulesPerKilogramDryAir),
            24 => Some(Self::BtusPerPoundDryAir),
            117 => Some(Self::BtusPerPound),
            127 => Some(Self::JoulesPerDegreeKelvin),
            151 => Some(Self::KilojoulesPerDegreeKelvin),
            152 => Some(Self::MegajoulesPerDegreeKelvin),
            128 => Some(Self::JoulesPerKilogramDegreeKelvin),
            153 => Some(Self::Newton),
            25 => Some(Self::CyclesPerHour),
            26 => Some(Self::CyclesPerMinute),
            27 => Some(Self::Hertz),
            129 => Some(Self::Kilohertz),
            130 => Some(Self::Megahertz),
            131 => Some(Self::PerHour),
            28 => Some(Self::GramsOfWaterPerKilogramDryAir),
            29 => Some(Self::PercentRelativeHumidity),
            194 => Some(Self::Micrometers),
            30 => Some(Self::Millimeters),
            118 => Some(Self::Centimeters),
            193 => Some(Self::Kilometers),
            31 => Some(Self::Meters),
            32 => Some(Self::Inches),
            33 => Some(Self::Feet),
            179 => Some(Self::Candelas),
            180 => Some(Self::CandelasPerSquareMeter),
            34 => Some(Self::WattsPerSquareFoot),
            35 => Some(Self::WattsPerSquareMeter),
            36 => Some(Self::Lumens),
            37 => Some(Self::Luxes),
            38 => Some(Self::FootCandles),
            196 => Some(Self::Milligrams),
            195 => Some(Self::Grams),
            39 => Some(Self::Kilograms),
            40 => Some(Self::PoundsMass),
            41 => Some(Self::Tons),
            154 => Some(Self::GramsPerSecond),
            155 => Some(Self::GramsPerMinute),
            42 => Some(Self::KilogramsPerSecond),
            43 => Some(Self::KilogramsPerMinute),
            44 => Some(Self::KilogramsPerHour),
            119 => Some(Self::PoundsMassPerSecond),
            45 => Some(Self::PoundsMassPerMinute),
            46 => Some(Self::PoundsMassPerHour),
            156 => Some(Self::TonsPerHour),
            132 => Some(Self::Milliwatts),
            47 => Some(Self::Watts),
            48 => Some(Self::Kilowatts),
            49 => Some(Self::Megawatts),
            50 => Some(Self::BtusPerHour),
            157 => Some(Self::KiloBtusPerHour),
            247 => Some(Self::JoulePerHours),
            51 => Some(Self::Horsepower),
            52 => Some(Self::TonsRefrigeration),
            53 => Some(Self::Pascals),
            133 => Some(Self::Hectopascals),
            54 => Some(Self::Kilopascals),
            134 => Some(Self::Millibars),
            55 => Some(Self::Bars),
            56 => Some(Self::PoundsForcePerSquareInch),
            206 => Some(Self::MillimetersOfWater),
            57 => Some(Self::CentimetersOfWater),
            58 => Some(Self::InchesOfWater),
            59 => Some(Self::MillimetersOfMercury),
            60 => Some(Self::CentimetersOfMercury),
            61 => Some(Self::InchesOfMercury),
            62 => Some(Self::DegreesCelsius),
            63 => Some(Self::DegreesKelvin),
            181 => Some(Self::DegreesKelvinPerHour),
            182 => Some(Self::DegreesKelvinPerMinute),
            64 => Some(Self::DegreesFahrenheit),
            65 => Some(Self::DegreeDaysCelsius),
            66 => Some(Self::DegreeDaysFahrenheit),
            120 => Some(Self::DeltaDegreesFahrenheit),
            121 => Some(Self::DeltaDegreesKelvin),
            67 => Some(Self::Years),
            68 => Some(Self::Months),
            69 => Some(Self::Weeks),
            70 => Some(Self::Days),
            71 => Some(Self::Hours),
            72 => Some(Self::Minutes),
            73 => Some(Self::Seconds),
            158 => Some(Self::HundredthsSeconds),
            159 => Some(Self::Milliseconds),
            160 => Some(Self::NewtonMeters),
            161 => Some(Self::MillimetersPerSecond),
            162 => Some(Self::MillimetersPerMinute),
            74 => Some(Self::MetersPerSecond),
            163 => Some(Self::MetersPerMinute),
            164 => Some(Self::MetersPerHour),
            75 => Some(Self::KilometersPerHour),
            76 => Some(Self::FeetPerSecond),
            77 => Some(Self::FeetPerMinute),
            78 => Some(Self::MilesPerHour),
            79 => Some(Self::CubicFeet),
            80 => Some(Self::CubicMeters),
            81 => Some(Self::ImperialGallons),
            197 => Some(Self::Milliliters),
            82 => Some(Self::Liters),
            83 => Some(Self::UsGallons),
            142 => Some(Self::CubicFeetPerSecond),
            84 => Some(Self::CubicFeetPerMinute),
            254 => Some(Self::MillionStandardCubicFeetPerMinute),
            191 => Some(Self::CubicFeetPerHour),
            248 => Some(Self::CubicFeetPerDay),
            47808 => Some(Self::StandardCubicFeetPerDay),
            47809 => Some(Self::MillionStandardCubicFeetPerDay),
            47810 => Some(Self::ThousandCubicFeetPerDay),
            47811 => Some(Self::ThousandStandardCubicFeetPerDay),
            47812 => Some(Self::PoundsMassPerDay),
            85 => Some(Self::CubicMetersPerSecond),
            165 => Some(Self::CubicMetersPerMinute),
            135 => Some(Self::CubicMetersPerHour),
            249 => Some(Self::CubicMetersPerDay),
            86 => Some(Self::ImperialGallonsPerMinute),
            198 => Some(Self::MillilitersPerSecond),
            87 => Some(Self::LitersPerSecond),
            88 => Some(Self::LitersPerMinute),
            136 => Some(Self::LitersPerHour),
            89 => Some(Self::UsGallonsPerMinute),
            192 => Some(Self::UsGallonsPerHour),
            90 => Some(Self::DegreesAngular),
            91 => Some(Self::DegreesCelsiusPerHour),
            92 => Some(Self::DegreesCelsiusPerMinute),
            93 => Some(Self::DegreesFahrenheitPerHour),
            94 => Some(Self::DegreesFahrenheitPerMinute),
            183 => Some(Self::JouleSeconds),
            186 => Some(Self::KilogramsPerCubicMeter),
            137 => Some(Self::KilowattHoursPerSquareMeter),
            138 => Some(Self::KilowattHoursPerSquareFoot),
            250 => Some(Self::WattHoursPerCubicMeter),
            251 => Some(Self::JoulesPerCubicMeter),
            139 => Some(Self::MegajoulesPerSquareMeter),
            140 => Some(Self::MegajoulesPerSquareFoot),
            252 => Some(Self::MolePercent),
            95 => Some(Self::NoUnits),
            187 => Some(Self::NewtonSeconds),
            188 => Some(Self::NewtonsPerMeter),
            96 => Some(Self::PartsPerMillion),
            97 => Some(Self::PartsPerBillion),
            253 => Some(Self::PascalSeconds),
            98 => Some(Self::Percent),
            143 => Some(Self::PercentObscurationPerFoot),
            144 => Some(Self::PercentObscurationPerMeter),
            99 => Some(Self::PercentPerSecond),
            100 => Some(Self::PerMinute),
            101 => Some(Self::PerSecond),
            102 => Some(Self::PsiPerDegreeFahrenheit),
            103 => Some(Self::Radians),
            184 => Some(Self::RadiansPerSecond),
            104 => Some(Self::RevolutionsPerMinute),
            185 => Some(Self::SquareMetersPerNewton),
            189 => Some(Self::WattsPerMeterPerDegreeKelvin),
            141 => Some(Self::WattsPerSquareMeterDegreeKelvin),
            207 => Some(Self::PerMille),
            208 => Some(Self::GramsPerGram),
            209 => Some(Self::KilogramsPerKilogram),
            210 => Some(Self::GramsPerKilogram),
            211 => Some(Self::MilligramsPerGram),
            212 => Some(Self::MilligramsPerKilogram),
            213 => Some(Self::GramsPerMilliliter),
            214 => Some(Self::GramsPerLiter),
            215 => Some(Self::MilligramsPerLiter),
            216 => Some(Self::MicrogramsPerLiter),
            217 => Some(Self::GramsPerCubicMeter),
            218 => Some(Self::MilligramsPerCubicMeter),
            219 => Some(Self::MicrogramsPerCubicMeter),
            220 => Some(Self::NanogramsPerCubicMeter),
            221 => Some(Self::GramsPerCubicCentimeter),
            222 => Some(Self::Becquerels),
            223 => Some(Self::Kilobecquerels),
            224 => Some(Self::Megabecquerels),
            225 => Some(Self::Gray),
            226 => Some(Self::Milligray),
            227 => Some(Self::Microgray),
            228 => Some(Self::Sieverts),
            229 => Some(Self::Millisieverts),
            230 => Some(Self::Microsieverts),
            231 => Some(Self::MicrosievertsPerHour),
            47814 => Some(Self::Millirems),
            47815 => Some(Self::MilliremsPerHour),
            232 => Some(Self::DecibelsA),
            233 => Some(Self::NephelometricTurbidityUnit),
            234 => Some(Self::PH),
            235 => Some(Self::GramsPerSquareMeter),
            236 => Some(Self::MinutesPerDegreeKelvin),
            _ => None,
        }
    }

    /// Get the category of this unit
    pub fn category(&self) -> &'static str {
        match *self as u32 {
            166 => "Acceleration",
            0..=1 | 115..=116 => "Area",
            105..=114 => "Currency",
            2..=15 | 122..=124 | 145 | 167..=178 | 199..=202 | 237 => "Electrical",
            16..=22 | 125..=126 | 146..=148 | 203..=205 | 238..=246 => "Energy",
            23..=24 | 117 => "Enthalpy",
            127..=128 | 151..=152 => "Entropy",
            153 => "Force",
            25..=27 | 129..=131 => "Frequency",
            28..=29 => "Humidity",
            30..=33 | 118 | 193..=194 => "Length",
            34..=38 | 179..=180 => "Light",
            39..=41 | 195..=196 => "Mass",
            42..=46 | 119 | 154..=156 => "Mass Flow",
            47..=52 | 132 | 157 => "Power",
            53..=61 | 133..=134 | 206 => "Pressure",
            62..=66 | 120..=121 | 181..=182 => "Temperature",
            67..=73 | 158..=159 => "Time",
            160 => "Torque",
            74..=78 | 161..=164 => "Velocity",
            79..=83 | 197 => "Volume",
            84..=89 | 135..=136 | 142 | 165 | 191..=192 | 198 | 248..=254 | 47808..=47812 => {
                "Volumetric Flow"
            }
            _ => "Other",
        }
    }
}

impl Default for EngineeringUnits {
    fn default() -> Self {
        Self::NoUnits
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_from_u32() {
        assert_eq!(
            EngineeringUnits::from_u32(95),
            Some(EngineeringUnits::NoUnits)
        );
        assert_eq!(
            EngineeringUnits::from_u32(62),
            Some(EngineeringUnits::DegreesCelsius)
        );
        assert_eq!(
            EngineeringUnits::from_u32(64),
            Some(EngineeringUnits::DegreesFahrenheit)
        );
        assert_eq!(EngineeringUnits::from_u32(999999), None);
    }

    #[test]
    fn test_category() {
        assert_eq!(EngineeringUnits::DegreesCelsius.category(), "Temperature");
        assert_eq!(EngineeringUnits::Watts.category(), "Power");
        assert_eq!(EngineeringUnits::Meters.category(), "Length");
    }

    #[test]
    fn test_default() {
        assert_eq!(EngineeringUnits::default(), EngineeringUnits::NoUnits);
    }
}
