use bacnet_macros::BacnetEnum;

/// BACnet object types
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, BacnetEnum)]
#[bacnet_enum(u16)]
pub enum ObjectType {
    #[bacnet_value(0)]
    AnalogInput,
    #[bacnet_value(1)]
    AnalogOutput,
    #[bacnet_value(2)]
    AnalogValue,
    #[bacnet_value(3)]
    BinaryInput,
    #[bacnet_value(4)]
    BinaryOutput,
    #[bacnet_value(5)]
    BinaryValue,
    #[bacnet_value(6)]
    Calendar,
    #[bacnet_value(7)]
    Command,
    #[bacnet_value(8)]
    Device,
    #[bacnet_value(9)]
    EventEnrollment,
    #[bacnet_value(10)]
    File,
    #[bacnet_value(11)]
    Group,
    #[bacnet_value(12)]
    Loop,
    #[bacnet_value(13)]
    MultiStateInput,
    #[bacnet_value(14)]
    MultiStateOutput,
    #[bacnet_value(15)]
    NotificationClass,
    #[bacnet_value(16)]
    Program,
    #[bacnet_value(17)]
    Schedule,
    #[bacnet_value(18)]
    Averaging,
    #[bacnet_value(19)]
    MultiStateValue,
    #[bacnet_value(20)]
    TrendLog,
    #[bacnet_value(21)]
    LifeSafetyPoint,
    #[bacnet_value(22)]
    LifeSafetyZone,
    #[bacnet_value(23)]
    Accumulator,
    #[bacnet_value(24)]
    PulseConverter,
    #[bacnet_value(25)]
    EventLog,
    #[bacnet_value(26)]
    GlobalGroup,
    #[bacnet_value(27)]
    TrendLogMultiple,
    #[bacnet_value(28)]
    LoadControl,
    #[bacnet_value(29)]
    StructuredView,
    #[bacnet_value(30)]
    AccessDoor,
    #[bacnet_value(31)]
    Timer,
    #[bacnet_value(32)]
    AccessCredential,
    #[bacnet_value(33)]
    AccessPoint,
    #[bacnet_value(34)]
    AccessRights,
    #[bacnet_value(35)]
    AccessUser,
    #[bacnet_value(36)]
    AccessZone,
    #[bacnet_value(37)]
    CredentialDataInput,
    #[bacnet_value(39)]
    BitstringValue,
    #[bacnet_value(40)]
    CharacterstringValue,
    #[bacnet_value(41)]
    DatepatternValue,
    #[bacnet_value(42)]
    DateValue,
    #[bacnet_value(43)]
    DatetimepatternValue,
    #[bacnet_value(44)]
    DatetimeValue,
    #[bacnet_value(45)]
    IntegerValue,
    #[bacnet_value(46)]
    LargeAnalogValue,
    #[bacnet_value(47)]
    OctetstringValue,
    #[bacnet_value(48)]
    PositiveIntegerValue,
    #[bacnet_value(49)]
    TimepatternValue,
    #[bacnet_value(50)]
    TimeValue,
    #[bacnet_value(51)]
    NotificationForwarder,
    #[bacnet_value(52)]
    AlertEnrollment,
    #[bacnet_value(53)]
    Channel,
    #[bacnet_value(54)]
    LightingOutput,
    #[bacnet_value(55)]
    BinaryLightingOutput,
    #[bacnet_value(56)]
    NetworkPort,
    #[bacnet_value(57)]
    ElevatorGroup,
    #[bacnet_value(58)]
    Escalator,
    #[bacnet_value(59)]
    Lift,
    #[bacnet_value(60)]
    Staging,
    #[bacnet_value(61)]
    AuditLog,
    #[bacnet_value(62)]
    AuditReporter,
    #[bacnet_value(63)]
    Color,
    #[bacnet_value(64)]
    ColorTemperature,
    // Vendor specific range starts at 128
    Custom(u16),
}
