/// BACnet property identifiers see clause 21.6 of the BACnet specification.
#[derive(Debug, PartialEq, Eq, Clone, Copy)]
pub enum PropertyIdentifier {
    AbsenteeLimit,
    AcceptedModes,
    AccessAlarmEvents,
    AccessDoors,
    AccessEvent,
    AccessEventAuthenticationFactor,
    AccessEventCredential,
    AccessEventTag,
    AccessEventTime,
    AccessTransactionEvents,
    Accompaniment,
    AccompanimentTime,
    AckRequired,
    AckedTransitions,
    Action,
    ActionText,
    ActivationTime,
    ActiveAuthenticationPolicy,
    ActiveCovMultipleSubscriptions,
    ActiveCovSubscriptions,
    ActiveText,
    ActiveVtSessions,
    ActualShedLevel,
    AdditionalReferencePorts,
    AdjustValue,
    AlarmValue,
    AlarmValues,
    AlignIntervals,
    All,
    AllWritesSuccessful,
    AllowGroupDelayInhibit,
    ApduLength,
    ApduSegmentTimeout,
    ApduTimeout,
    ApplicationSoftwareVersion,
    Archive,
    AssignedAccessRights,
    AssignedLandingCalls,
    AttemptedSamples,
    AuditSourceReporter,
    AuditLevel,
    AuditNotificationRecipient,
    AuditPriorityFilter,
    AuditableOperations,
    AuthenticationFactors,
    AuthenticationPolicyList,
    AuthenticationPolicyNames,
    AuthenticationStatus,
    AuthorizationCache,
    AuthorizationExemptions,
    AuthorizationGroups,
    AuthorizationMode,
    AuthorizationPolicy,
    AuthorizationScope,
    AuthorizationServer,
    AuthorizationStatus,
    AutoSubordinateDiscovery,
    AverageValue,
    BackupAndRestoreState,
    BackupFailureTimeout,
    BackupPreparationTime,
    BacnetIpGlobalAddress,
    BacnetIpMode,
    BacnetIpMulticastAddress,
    BacnetIpNatTraversal,
    BacnetIpUdpPort,
    BacnetIpv6Mode,
    BacnetIpv6UdpPort,
    BacnetIpv6MulticastAddress,
    BbmdAcceptFdRegistrations,
    BbmdBroadcastDistributionTable,
    BbmdForeignDeviceTable,
    BelongsTo,
    Bias,
    BitMask,
    BitText,
    BlinkWarnEnable,
    BufferSize,
    CarAssignedDirection,
    CarDoorCommand,
    CarDoorStatus,
    CarDoorText,
    CarDoorZone,
    CarDriveStatus,
    CarLoad,
    CarLoadUnits,
    CarMode,
    CarMovingDirection,
    CarPosition,
    CertificateSigningRequestFile,
    ChangeOfStateCount,
    ChangeOfStateTime,
    ChangesPending,
    ChannelNumber,
    ClientCovIncrement,
    ColorCommand,
    ColorOverride,
    ColorReference,
    Command,
    CommandTimeArray,
    CommandValidationResult,
    ConfigurationFiles,
    ControlGroups,
    ControlledVariableReference,
    ControlledVariableUnits,
    ControlledVariableValue,
    Count,
    CountBeforeChange,
    CountChangeTime,
    CovIncrement,
    CovPeriod,
    CovResubscriptionInterval,
    CovuPeriod,
    CovuRecipients,
    CredentialDisable,
    CredentialStatus,
    Credentials,
    CredentialsInZone,
    CurrentCommandPriority,
    CurrentHealth,
    DatabaseRevision,
    DateList,
    DaylightSavingsStatus,
    DaysRemaining,
    Deadband,
    DefaultColor,
    DefaultColorTemperature,
    DefaultFadeTime,
    DefaultPresentValue,
    DefaultRampRate,
    DefaultStepIncrement,
    DefaultSubordinateRelationship,
    DefaultTimeout,
    DeleteOnForward,
    DefaultOnValue,
    DeployedProfileLocation,
    DerivativeConstant,
    DerivativeConstantUnits,
    Description,
    DescriptionOfHalt,
    DeviceAddressBinding,
    DeviceAddressProxyEnable,
    DeviceAddressProxyTable,
    DeviceAddressProxyTimeout,
    DeviceType,
    DeviceUuid,
    DirectReading,
    DoorAlarmState,
    DoorExtendedPulseTime,
    DoorMembers,
    DoorOpenTooLongTime,
    DoorPulseTime,
    DoorStatus,
    DoorUnlockDelayTime,
    DutyWindow,
    EffectivePeriod,
    EgressActive,
    EgressTime,
    ElapsedActiveTime,
    ElevatorGroup,
    Enable,
    EnergyMeter,
    EnergyMeterRef,
    EntryPoints,
    ErrorLimit,
    EscalatorMode,
    EventAlgorithmInhibit,
    EventAlgorithmInhibitRef,
    EventDetectionEnable,
    EventEnable,
    EventMessageTexts,
    EventMessageTextsConfig,
    EventParameters,
    EventState,
    EventTimeStamps,
    EventType,
    ExceptionSchedule,
    ExecutionDelay,
    ExitPoints,
    ExpectedShedLevel,
    ExpirationTime,
    ExtendedTimeEnable,
    FailedAttemptEvents,
    FailedAttempts,
    FailedAttemptsTime,
    FaultHighLimit,
    FaultLowLimit,
    FaultParameters,
    FaultSignals,
    FaultType,
    FaultValues,
    FdBbmdAddress,
    FdSubscriptionLifetime,
    FeedbackValue,
    FileAccessMethod,
    FileSize,
    FileType,
    FirmwareRevision,
    FloorNumber,
    FloorText,
    FullDutyBaseline,
    GlobalIdentifier,
    GroupId,
    GroupMemberNames,
    GroupMembers,
    GroupMode,
    HighEndTrim,
    HighLimit,
    HigherDeck,
    InProcess,
    InProgress,
    InactiveText,
    InitialTimeout,
    InputReference,
    InstallationId,
    InstanceOf,
    InstantaneousPower,
    IntegralConstant,
    IntegralConstantUnits,
    InterfaceValue,
    IntervalOffset,
    IpAddress,
    IpDefaultGateway,
    IpDhcpEnable,
    IpDhcpLeaseTime,
    IpDhcpLeaseTimeRemaining,
    IpDhcpServer,
    IpDnsServer,
    IpSubnetMask,
    Ipv6Address,
    Ipv6AutoAddressingEnable,
    Ipv6DefaultGateway,
    Ipv6DhcpLeaseTime,
    Ipv6DhcpLeaseTimeRemaining,
    Ipv6DhcpServer,
    Ipv6DnsServer,
    Ipv6PrefixLength,
    Ipv6ZoneIndex,
    IssueConfirmedNotifications,
    IssuerCertificateFiles,
    IsUtc,
    LandingCallControl,
    LandingCalls,
    LandingDoorStatus,
    LastAccessEvent,
    LastAccessPoint,
    LastCommandTime,
    LastCredentialAdded,
    LastCredentialAddedTime,
    LastCredentialRemoved,
    LastCredentialRemovedTime,
    LastNotifyRecord,
    LastOnValue,
    LastPriority,
    LastRestartReason,
    LastRestoreTime,
    LastStateChange,
    LastUseTime,
    LifeSafetyAlarmValues,
    LightingCommand,
    LightingCommandDefaultPriority,
    LimitEnable,
    LimitMonitoringInterval,
    LinkSpeed,
    LinkSpeedAutonegotiate,
    LinkSpeeds,
    ListOfGroupMembers,
    ListOfObjectPropertyReferences,
    LocalDate,
    LocalForwardingOnly,
    LocalTime,
    Location,
    LockStatus,
    Lockout,
    LockoutRelinquishTime,
    LogBuffer,
    LogDeviceObjectProperty,
    LogInterval,
    LoggingObject,
    LoggingRecord,
    LoggingType,
    LowDiffLimit,
    LowEndTrim,
    LowLimit,
    LowerDeck,
    MacAddress,
    MachineRoomId,
    MaintenanceRequired,
    MakingCarCall,
    ManipulatedVariableReference,
    ManualSubordinateAddressBinding,
    MaskedAlarmValues,
    MaxActualValue,
    MaxApduLengthAccepted,
    MaxBvlcLengthAccepted,
    MaxFailedAttempts,
    MaxProxiedIAmsPerSecond,
    MaxInfoFrames,
    MaxManager,
    MaxNpduLengthAccepted,
    MaxPresValue,
    MaxSegmentsAccepted,
    MaximumOutput,
    MaximumSendDelay,
    MaximumValue,
    MaximumValueTimestamp,
    MemberOf,
    MemberStatusFlags,
    Members,
    MinActualValue,
    MinPresValue,
    MinimumOffTime,
    MinimumOnTime,
    MinimumOutput,
    MinimumValue,
    MinimumValueTimestamp,
    Mode,
    ModelName,
    ModificationDate,
    MonitoredObjects,
    MusterPoint,
    NegativeAccessRules,
    NetworkInterfaceName,
    NetworkNumber,
    NetworkNumberQuality,
    NetworkType,
    NextStoppingFloor,
    NodeSubtype,
    NodeType,
    NotificationClass,
    NotificationThreshold,
    NotifyType,
    NumberOfApduRetries,
    NumberOfAuthenticationPolicies,
    NumberOfStates,
    ObjectIdentifier,
    ObjectList,
    ObjectName,
    ObjectPropertyReference,
    ObjectType,
    OccupancyCount,
    OccupancyCountAdjust,
    OccupancyCountEnable,
    OccupancyLowerLimit,
    OccupancyLowerLimitEnforced,
    OccupancyState,
    OccupancyUpperLimit,
    OccupancyUpperLimitEnforced,
    OperationDirection,
    OperationExpected,
    OperationalCertificateFile,
    Optional,
    OutOfService,
    OutputUnits,
    OverrideColorReference,
    PassbackMode,
    PassbackTimeout,
    PassengerAlarm,
    Polarity,
    PortFilter,
    PositiveAccessRules,
    Power,
    PowerMode,
    Prescale,
    PresentStage,
    PresentValue,
    Priority,
    PriorityArray,
    PriorityForWriting,
    ProcessIdentifier,
    ProcessIdentifierFilter,
    ProfileLocation,
    ProfileName,
    ProgramChange,
    ProgramLocation,
    ProgramState,
    PropertyList,
    ProportionalConstant,
    ProportionalConstantUnits,
    ProtocolLevel,
    ProtocolObjectTypesSupported,
    ProtocolRevision,
    ProtocolServicesSupported,
    ProtocolVersion,
    PulseRate,
    ReadOnly,
    ReasonForDisable,
    ReasonForHalt,
    RecipientList,
    RecordCount,
    RecordsSinceNotification,
    ReferencePort,
    RegisteredCarCall,
    Reliability,
    ReliabilityEvaluationInhibit,
    RelinquishDefault,
    Represents,
    RequestedShedLevel,
    RequestedUpdateInterval,
    Required,
    Resolution,
    RestartNotificationRecipients,
    RestoreCompletionTime,
    RestorePreparationTime,
    RoutingTable,
    ScConnectWaitTimeout,
    ScDirectConnectAcceptEnable,
    ScDirectConnectAcceptUris,
    ScDirectConnectBinding,
    ScDirectConnectConnectionStatus,
    ScDirectConnectInitiateEnable,
    ScDisconnectWaitTimeout,
    ScFailedConnectionRequests,
    ScFailoverHubConnectionStatus,
    ScFailoverHubUri,
    ScHubConnectorState,
    ScHubFunctionAcceptUris,
    ScHubFunctionBinding,
    ScHubFunctionConnectionStatus,
    ScHubFunctionEnable,
    ScHeartbeatTimeout,
    ScPrimaryHubConnectionStatus,
    ScPrimaryHubUri,
    ScMaximumReconnectTime,
    ScMinimumReconnectTime,
    Scale,
    ScaleFactor,
    ScheduleDefault,
    SecuredStatus,
    SegmentationSupported,
    SendNow,
    SerialNumber,
    Setpoint,
    SetpointReference,
    Setting,
    ShedDuration,
    ShedLevelDescriptions,
    ShedLevels,
    Silenced,
    Stages,
    StageNames,
    StartTime,
    StateChangeValues,
    StateDescription,
    StateText,
    StatusFlags,
    StopTime,
    StopWhenFull,
    StrikeCount,
    StructuredObjectList,
    SubordinateAddressBinding,
    SubordinateAnnotations,
    SubordinateList,
    SubordinateNodeTypes,
    SubordinateProxyEnable,
    SubordinateRelationships,
    SubordinateTags,
    SubscribedRecipients,
    SupportedFormatClasses,
    SupportedFormats,
    SystemStatus,
    Tags,
    TargetReferences,
    ThreatAuthority,
    ThreatLevel,
    TimeDelay,
    TimeDelayNormal,
    TimeOfActiveTimeReset,
    TimeOfDeviceRestart,
    TimeOfStateCountReset,
    TimeOfStrikeCountReset,
    TimeSynchronizationInterval,
    TimeSynchronizationRecipients,
    TimerRunning,
    TimerState,
    TotalRecordCount,
    TraceFlag,
    TrackingValue,
    TransactionNotificationClass,
    Transition,
    Trigger,
    TrimFadeTime,
    Units,
    UpdateInterval,
    UpdateTime,
    UserExternalIdentifier,
    UserInformationReference,
    UserName,
    UserType,
    UsesRemaining,
    UtcOffset,
    UtcTimeSynchronizationRecipients,
    ValidSamples,
    ValueBeforeChange,
    ValueChangeTime,
    ValueSet,
    ValueSource,
    ValueSourceArray,
    VarianceValue,
    VendorIdentifier,
    VendorName,
    VerificationTime,
    VirtualMacAddressTable,
    VtClassesSupported,
    WeeklySchedule,
    WindowInterval,
    WindowSamples,
    WriteEveryScheduledAction,
    WriteStatus,
    ZoneFrom,
    ZoneMembers,
    ZoneTo,
    Custom(u32),
}

impl From<PropertyIdentifier> for u32 {
    fn from(val: PropertyIdentifier) -> Self {
        match val {
            PropertyIdentifier::AbsenteeLimit => 244,
            PropertyIdentifier::AcceptedModes => 175,
            PropertyIdentifier::AccessAlarmEvents => 245,
            PropertyIdentifier::AccessDoors => 246,
            PropertyIdentifier::AccessEvent => 247,
            PropertyIdentifier::AccessEventAuthenticationFactor => 248,
            PropertyIdentifier::AccessEventCredential => 249,
            PropertyIdentifier::AccessEventTag => 322,
            PropertyIdentifier::AccessEventTime => 250,
            PropertyIdentifier::AccessTransactionEvents => 251,
            PropertyIdentifier::Accompaniment => 252,
            PropertyIdentifier::AccompanimentTime => 253,
            PropertyIdentifier::AckRequired => 1,
            PropertyIdentifier::AckedTransitions => 0,
            PropertyIdentifier::Action => 2,
            PropertyIdentifier::ActionText => 3,
            PropertyIdentifier::ActivationTime => 254,
            PropertyIdentifier::ActiveAuthenticationPolicy => 255,
            PropertyIdentifier::ActiveCovMultipleSubscriptions => 481,
            PropertyIdentifier::ActiveCovSubscriptions => 152,
            PropertyIdentifier::ActiveText => 4,
            PropertyIdentifier::ActiveVtSessions => 5,
            PropertyIdentifier::ActualShedLevel => 212,
            PropertyIdentifier::AdditionalReferencePorts => 508,
            PropertyIdentifier::AdjustValue => 176,
            PropertyIdentifier::AlarmValue => 6,
            PropertyIdentifier::AlarmValues => 7,
            PropertyIdentifier::AlignIntervals => 193,
            PropertyIdentifier::All => 8,
            PropertyIdentifier::AllWritesSuccessful => 9,
            PropertyIdentifier::AllowGroupDelayInhibit => 365,
            PropertyIdentifier::ApduLength => 399,
            PropertyIdentifier::ApduSegmentTimeout => 10,
            PropertyIdentifier::ApduTimeout => 11,
            PropertyIdentifier::ApplicationSoftwareVersion => 12,
            PropertyIdentifier::Archive => 13,
            PropertyIdentifier::AssignedAccessRights => 256,
            PropertyIdentifier::AssignedLandingCalls => 447,
            PropertyIdentifier::AttemptedSamples => 124,
            PropertyIdentifier::AuditSourceReporter => 497,
            PropertyIdentifier::AuditLevel => 498,
            PropertyIdentifier::AuditNotificationRecipient => 499,
            PropertyIdentifier::AuditPriorityFilter => 500,
            PropertyIdentifier::AuditableOperations => 501,
            PropertyIdentifier::AuthenticationFactors => 257,
            PropertyIdentifier::AuthenticationPolicyList => 258,
            PropertyIdentifier::AuthenticationPolicyNames => 259,
            PropertyIdentifier::AuthenticationStatus => 260,
            PropertyIdentifier::AuthorizationCache => 4194343,
            PropertyIdentifier::AuthorizationExemptions => 364,
            PropertyIdentifier::AuthorizationGroups => 4194344,
            PropertyIdentifier::AuthorizationMode => 261,
            PropertyIdentifier::AuthorizationPolicy => 4194345,
            PropertyIdentifier::AuthorizationScope => 4194346,
            PropertyIdentifier::AuthorizationServer => 4194347,
            PropertyIdentifier::AuthorizationStatus => 4194348,
            PropertyIdentifier::AutoSubordinateDiscovery => 169,
            PropertyIdentifier::AverageValue => 125,
            PropertyIdentifier::BackupAndRestoreState => 338,
            PropertyIdentifier::BackupFailureTimeout => 153,
            PropertyIdentifier::BackupPreparationTime => 339,
            PropertyIdentifier::BacnetIpGlobalAddress => 407,
            PropertyIdentifier::BacnetIpMode => 408,
            PropertyIdentifier::BacnetIpMulticastAddress => 409,
            PropertyIdentifier::BacnetIpNatTraversal => 410,
            PropertyIdentifier::BacnetIpUdpPort => 412,
            PropertyIdentifier::BacnetIpv6Mode => 435,
            PropertyIdentifier::BacnetIpv6UdpPort => 438,
            PropertyIdentifier::BacnetIpv6MulticastAddress => 440,
            PropertyIdentifier::BbmdAcceptFdRegistrations => 413,
            PropertyIdentifier::BbmdBroadcastDistributionTable => 414,
            PropertyIdentifier::BbmdForeignDeviceTable => 415,
            PropertyIdentifier::BelongsTo => 262,
            PropertyIdentifier::Bias => 14,
            PropertyIdentifier::BitMask => 342,
            PropertyIdentifier::BitText => 343,
            PropertyIdentifier::BlinkWarnEnable => 373,
            PropertyIdentifier::BufferSize => 126,
            PropertyIdentifier::CarAssignedDirection => 448,
            PropertyIdentifier::CarDoorCommand => 449,
            PropertyIdentifier::CarDoorStatus => 450,
            PropertyIdentifier::CarDoorText => 451,
            PropertyIdentifier::CarDoorZone => 452,
            PropertyIdentifier::CarDriveStatus => 453,
            PropertyIdentifier::CarLoad => 454,
            PropertyIdentifier::CarLoadUnits => 455,
            PropertyIdentifier::CarMode => 456,
            PropertyIdentifier::CarMovingDirection => 457,
            PropertyIdentifier::CarPosition => 458,
            PropertyIdentifier::CertificateSigningRequestFile => 509,
            PropertyIdentifier::ChangeOfStateCount => 15,
            PropertyIdentifier::ChangeOfStateTime => 16,
            PropertyIdentifier::ChangesPending => 416,
            PropertyIdentifier::ChannelNumber => 366,
            PropertyIdentifier::ClientCovIncrement => 127,
            PropertyIdentifier::ColorCommand => 4194334,
            PropertyIdentifier::ColorOverride => 4194328,
            PropertyIdentifier::ColorReference => 4194329,
            PropertyIdentifier::Command => 417,
            PropertyIdentifier::CommandTimeArray => 430,
            PropertyIdentifier::CommandValidationResult => 510,
            PropertyIdentifier::ConfigurationFiles => 154,
            PropertyIdentifier::ControlGroups => 367,
            PropertyIdentifier::ControlledVariableReference => 19,
            PropertyIdentifier::ControlledVariableUnits => 20,
            PropertyIdentifier::ControlledVariableValue => 21,
            PropertyIdentifier::Count => 177,
            PropertyIdentifier::CountBeforeChange => 178,
            PropertyIdentifier::CountChangeTime => 179,
            PropertyIdentifier::CovIncrement => 22,
            PropertyIdentifier::CovPeriod => 180,
            PropertyIdentifier::CovResubscriptionInterval => 128,
            PropertyIdentifier::CovuPeriod => 349,
            PropertyIdentifier::CovuRecipients => 350,
            PropertyIdentifier::CredentialDisable => 263,
            PropertyIdentifier::CredentialStatus => 264,
            PropertyIdentifier::Credentials => 265,
            PropertyIdentifier::CredentialsInZone => 266,
            PropertyIdentifier::CurrentCommandPriority => 431,
            PropertyIdentifier::CurrentHealth => 4194307,
            PropertyIdentifier::DatabaseRevision => 155,
            PropertyIdentifier::DateList => 23,
            PropertyIdentifier::DaylightSavingsStatus => 24,
            PropertyIdentifier::DaysRemaining => 267,
            PropertyIdentifier::Deadband => 25,
            PropertyIdentifier::DefaultColor => 4194330,
            PropertyIdentifier::DefaultColorTemperature => 4194331,
            PropertyIdentifier::DefaultFadeTime => 374,
            PropertyIdentifier::DefaultPresentValue => 492,
            PropertyIdentifier::DefaultRampRate => 375,
            PropertyIdentifier::DefaultStepIncrement => 376,
            PropertyIdentifier::DefaultSubordinateRelationship => 490,
            PropertyIdentifier::DefaultTimeout => 393,
            PropertyIdentifier::DeleteOnForward => 502,
            PropertyIdentifier::DefaultOnValue => 4194341,
            PropertyIdentifier::DeployedProfileLocation => 484,
            PropertyIdentifier::DerivativeConstant => 26,
            PropertyIdentifier::DerivativeConstantUnits => 27,
            PropertyIdentifier::Description => 28,
            PropertyIdentifier::DescriptionOfHalt => 29,
            PropertyIdentifier::DeviceAddressBinding => 30,
            PropertyIdentifier::DeviceAddressProxyEnable => 4194338,
            PropertyIdentifier::DeviceAddressProxyTable => 4194339,
            PropertyIdentifier::DeviceAddressProxyTimeout => 4194340,
            PropertyIdentifier::DeviceType => 31,
            PropertyIdentifier::DeviceUuid => 507,
            PropertyIdentifier::DirectReading => 156,
            PropertyIdentifier::DoorAlarmState => 226,
            PropertyIdentifier::DoorExtendedPulseTime => 227,
            PropertyIdentifier::DoorMembers => 228,
            PropertyIdentifier::DoorOpenTooLongTime => 229,
            PropertyIdentifier::DoorPulseTime => 230,
            PropertyIdentifier::DoorStatus => 231,
            PropertyIdentifier::DoorUnlockDelayTime => 232,
            PropertyIdentifier::DutyWindow => 213,
            PropertyIdentifier::EffectivePeriod => 32,
            PropertyIdentifier::EgressActive => 386,
            PropertyIdentifier::EgressTime => 377,
            PropertyIdentifier::ElapsedActiveTime => 33,
            PropertyIdentifier::ElevatorGroup => 459,
            PropertyIdentifier::Enable => 133,
            PropertyIdentifier::EnergyMeter => 460,
            PropertyIdentifier::EnergyMeterRef => 461,
            PropertyIdentifier::EntryPoints => 268,
            PropertyIdentifier::ErrorLimit => 34,
            PropertyIdentifier::EscalatorMode => 462,
            PropertyIdentifier::EventAlgorithmInhibit => 354,
            PropertyIdentifier::EventAlgorithmInhibitRef => 355,
            PropertyIdentifier::EventDetectionEnable => 353,
            PropertyIdentifier::EventEnable => 35,
            PropertyIdentifier::EventMessageTexts => 351,
            PropertyIdentifier::EventMessageTextsConfig => 352,
            PropertyIdentifier::EventParameters => 83,
            PropertyIdentifier::EventState => 36,
            PropertyIdentifier::EventTimeStamps => 130,
            PropertyIdentifier::EventType => 37,
            PropertyIdentifier::ExceptionSchedule => 38,
            PropertyIdentifier::ExecutionDelay => 368,
            PropertyIdentifier::ExitPoints => 269,
            PropertyIdentifier::ExpectedShedLevel => 214,
            PropertyIdentifier::ExpirationTime => 270,
            PropertyIdentifier::ExtendedTimeEnable => 271,
            PropertyIdentifier::FailedAttemptEvents => 272,
            PropertyIdentifier::FailedAttempts => 273,
            PropertyIdentifier::FailedAttemptsTime => 274,
            PropertyIdentifier::FaultHighLimit => 388,
            PropertyIdentifier::FaultLowLimit => 389,
            PropertyIdentifier::FaultParameters => 358,
            PropertyIdentifier::FaultSignals => 463,
            PropertyIdentifier::FaultType => 359,
            PropertyIdentifier::FaultValues => 39,
            PropertyIdentifier::FdBbmdAddress => 418,
            PropertyIdentifier::FdSubscriptionLifetime => 419,
            PropertyIdentifier::FeedbackValue => 40,
            PropertyIdentifier::FileAccessMethod => 41,
            PropertyIdentifier::FileSize => 42,
            PropertyIdentifier::FileType => 43,
            PropertyIdentifier::FirmwareRevision => 44,
            PropertyIdentifier::FloorNumber => 506,
            PropertyIdentifier::FloorText => 464,
            PropertyIdentifier::FullDutyBaseline => 215,
            PropertyIdentifier::GlobalIdentifier => 323,
            PropertyIdentifier::GroupId => 465,
            PropertyIdentifier::GroupMemberNames => 346,
            PropertyIdentifier::GroupMembers => 345,
            PropertyIdentifier::GroupMode => 467,
            PropertyIdentifier::HighEndTrim => 4194335,
            PropertyIdentifier::HighLimit => 45,
            PropertyIdentifier::HigherDeck => 468,
            PropertyIdentifier::InProcess => 47,
            PropertyIdentifier::InProgress => 378,
            PropertyIdentifier::InactiveText => 46,
            PropertyIdentifier::InitialTimeout => 394,
            PropertyIdentifier::InputReference => 181,
            PropertyIdentifier::InstallationId => 469,
            PropertyIdentifier::InstanceOf => 48,
            PropertyIdentifier::InstantaneousPower => 379,
            PropertyIdentifier::IntegralConstant => 49,
            PropertyIdentifier::IntegralConstantUnits => 50,
            PropertyIdentifier::InterfaceValue => 387,
            PropertyIdentifier::IntervalOffset => 195,
            PropertyIdentifier::IpAddress => 400,
            PropertyIdentifier::IpDefaultGateway => 401,
            PropertyIdentifier::IpDhcpEnable => 402,
            PropertyIdentifier::IpDhcpLeaseTime => 403,
            PropertyIdentifier::IpDhcpLeaseTimeRemaining => 404,
            PropertyIdentifier::IpDhcpServer => 405,
            PropertyIdentifier::IpDnsServer => 406,
            PropertyIdentifier::IpSubnetMask => 411,
            PropertyIdentifier::Ipv6Address => 436,
            PropertyIdentifier::Ipv6AutoAddressingEnable => 442,
            PropertyIdentifier::Ipv6DefaultGateway => 439,
            PropertyIdentifier::Ipv6DhcpLeaseTime => 443,
            PropertyIdentifier::Ipv6DhcpLeaseTimeRemaining => 444,
            PropertyIdentifier::Ipv6DhcpServer => 445,
            PropertyIdentifier::Ipv6DnsServer => 441,
            PropertyIdentifier::Ipv6PrefixLength => 437,
            PropertyIdentifier::Ipv6ZoneIndex => 446,
            PropertyIdentifier::IssueConfirmedNotifications => 51,
            PropertyIdentifier::IssuerCertificateFiles => 511,
            PropertyIdentifier::IsUtc => 344,
            PropertyIdentifier::LandingCallControl => 471,
            PropertyIdentifier::LandingCalls => 470,
            PropertyIdentifier::LandingDoorStatus => 472,
            PropertyIdentifier::LastAccessEvent => 275,
            PropertyIdentifier::LastAccessPoint => 276,
            PropertyIdentifier::LastCommandTime => 432,
            PropertyIdentifier::LastCredentialAdded => 277,
            PropertyIdentifier::LastCredentialAddedTime => 278,
            PropertyIdentifier::LastCredentialRemoved => 279,
            PropertyIdentifier::LastCredentialRemovedTime => 280,
            PropertyIdentifier::LastNotifyRecord => 173,
            PropertyIdentifier::LastOnValue => 4194342,
            PropertyIdentifier::LastPriority => 369,
            PropertyIdentifier::LastRestartReason => 196,
            PropertyIdentifier::LastRestoreTime => 157,
            PropertyIdentifier::LastStateChange => 395,
            PropertyIdentifier::LastUseTime => 281,
            PropertyIdentifier::LifeSafetyAlarmValues => 166,
            PropertyIdentifier::LightingCommand => 380,
            PropertyIdentifier::LightingCommandDefaultPriority => 381,
            PropertyIdentifier::LimitEnable => 52,
            PropertyIdentifier::LimitMonitoringInterval => 182,
            PropertyIdentifier::LinkSpeed => 420,
            PropertyIdentifier::LinkSpeedAutonegotiate => 422,
            PropertyIdentifier::LinkSpeeds => 421,
            PropertyIdentifier::ListOfGroupMembers => 53,
            PropertyIdentifier::ListOfObjectPropertyReferences => 54,
            PropertyIdentifier::LocalDate => 56,
            PropertyIdentifier::LocalForwardingOnly => 360,
            PropertyIdentifier::LocalTime => 57,
            PropertyIdentifier::Location => 58,
            PropertyIdentifier::LockStatus => 233,
            PropertyIdentifier::Lockout => 282,
            PropertyIdentifier::LockoutRelinquishTime => 283,
            PropertyIdentifier::LogBuffer => 131,
            PropertyIdentifier::LogDeviceObjectProperty => 132,
            PropertyIdentifier::LogInterval => 134,
            PropertyIdentifier::LoggingObject => 183,
            PropertyIdentifier::LoggingRecord => 184,
            PropertyIdentifier::LoggingType => 197,
            PropertyIdentifier::LowDiffLimit => 390,
            PropertyIdentifier::LowEndTrim => 4194336,
            PropertyIdentifier::LowLimit => 59,
            PropertyIdentifier::LowerDeck => 473,
            PropertyIdentifier::MacAddress => 423,
            PropertyIdentifier::MachineRoomId => 474,
            PropertyIdentifier::MaintenanceRequired => 158,
            PropertyIdentifier::MakingCarCall => 475,
            PropertyIdentifier::ManipulatedVariableReference => 60,
            PropertyIdentifier::ManualSubordinateAddressBinding => 170,
            PropertyIdentifier::MaskedAlarmValues => 234,
            PropertyIdentifier::MaxActualValue => 382,
            PropertyIdentifier::MaxApduLengthAccepted => 62,
            PropertyIdentifier::MaxBvlcLengthAccepted => 4194304,
            PropertyIdentifier::MaxFailedAttempts => 285,
            PropertyIdentifier::MaxProxiedIAmsPerSecond => 4194349,
            PropertyIdentifier::MaxInfoFrames => 63,
            PropertyIdentifier::MaxManager => 64,
            PropertyIdentifier::MaxNpduLengthAccepted => 4194305,
            PropertyIdentifier::MaxPresValue => 65,
            PropertyIdentifier::MaxSegmentsAccepted => 167,
            PropertyIdentifier::MaximumOutput => 61,
            PropertyIdentifier::MaximumSendDelay => 503,
            PropertyIdentifier::MaximumValue => 135,
            PropertyIdentifier::MaximumValueTimestamp => 149,
            PropertyIdentifier::MemberOf => 159,
            PropertyIdentifier::MemberStatusFlags => 347,
            PropertyIdentifier::Members => 286,
            PropertyIdentifier::MinActualValue => 383,
            PropertyIdentifier::MinPresValue => 69,
            PropertyIdentifier::MinimumOffTime => 66,
            PropertyIdentifier::MinimumOnTime => 67,
            PropertyIdentifier::MinimumOutput => 68,
            PropertyIdentifier::MinimumValue => 136,
            PropertyIdentifier::MinimumValueTimestamp => 150,
            PropertyIdentifier::Mode => 160,
            PropertyIdentifier::ModelName => 70,
            PropertyIdentifier::ModificationDate => 71,
            PropertyIdentifier::MonitoredObjects => 504,
            PropertyIdentifier::MusterPoint => 287,
            PropertyIdentifier::NegativeAccessRules => 288,
            PropertyIdentifier::NetworkInterfaceName => 424,
            PropertyIdentifier::NetworkNumber => 425,
            PropertyIdentifier::NetworkNumberQuality => 426,
            PropertyIdentifier::NetworkType => 427,
            PropertyIdentifier::NextStoppingFloor => 476,
            PropertyIdentifier::NodeSubtype => 207,
            PropertyIdentifier::NodeType => 208,
            PropertyIdentifier::NotificationClass => 17,
            PropertyIdentifier::NotificationThreshold => 137,
            PropertyIdentifier::NotifyType => 72,
            PropertyIdentifier::NumberOfApduRetries => 73,
            PropertyIdentifier::NumberOfAuthenticationPolicies => 289,
            PropertyIdentifier::NumberOfStates => 74,
            PropertyIdentifier::ObjectIdentifier => 75,
            PropertyIdentifier::ObjectList => 76,
            PropertyIdentifier::ObjectName => 77,
            PropertyIdentifier::ObjectPropertyReference => 78,
            PropertyIdentifier::ObjectType => 79,
            PropertyIdentifier::OccupancyCount => 290,
            PropertyIdentifier::OccupancyCountAdjust => 291,
            PropertyIdentifier::OccupancyCountEnable => 292,
            PropertyIdentifier::OccupancyLowerLimit => 294,
            PropertyIdentifier::OccupancyLowerLimitEnforced => 295,
            PropertyIdentifier::OccupancyState => 296,
            PropertyIdentifier::OccupancyUpperLimit => 297,
            PropertyIdentifier::OccupancyUpperLimitEnforced => 298,
            PropertyIdentifier::OperationDirection => 477,
            PropertyIdentifier::OperationExpected => 161,
            PropertyIdentifier::OperationalCertificateFile => 4194306,
            PropertyIdentifier::Optional => 80,
            PropertyIdentifier::OutOfService => 81,
            PropertyIdentifier::OutputUnits => 82,
            PropertyIdentifier::OverrideColorReference => 4194332,
            PropertyIdentifier::PassbackMode => 300,
            PropertyIdentifier::PassbackTimeout => 301,
            PropertyIdentifier::PassengerAlarm => 478,
            PropertyIdentifier::Polarity => 84,
            PropertyIdentifier::PortFilter => 363,
            PropertyIdentifier::PositiveAccessRules => 302,
            PropertyIdentifier::Power => 384,
            PropertyIdentifier::PowerMode => 479,
            PropertyIdentifier::Prescale => 185,
            PropertyIdentifier::PresentStage => 493,
            PropertyIdentifier::PresentValue => 85,
            PropertyIdentifier::Priority => 86,
            PropertyIdentifier::PriorityArray => 87,
            PropertyIdentifier::PriorityForWriting => 88,
            PropertyIdentifier::ProcessIdentifier => 89,
            PropertyIdentifier::ProcessIdentifierFilter => 361,
            PropertyIdentifier::ProfileLocation => 485,
            PropertyIdentifier::ProfileName => 168,
            PropertyIdentifier::ProgramChange => 90,
            PropertyIdentifier::ProgramLocation => 91,
            PropertyIdentifier::ProgramState => 92,
            PropertyIdentifier::PropertyList => 371,
            PropertyIdentifier::ProportionalConstant => 93,
            PropertyIdentifier::ProportionalConstantUnits => 94,
            PropertyIdentifier::ProtocolLevel => 482,
            PropertyIdentifier::ProtocolObjectTypesSupported => 96,
            PropertyIdentifier::ProtocolRevision => 139,
            PropertyIdentifier::ProtocolServicesSupported => 97,
            PropertyIdentifier::ProtocolVersion => 98,
            PropertyIdentifier::PulseRate => 186,
            PropertyIdentifier::ReadOnly => 99,
            PropertyIdentifier::ReasonForDisable => 303,
            PropertyIdentifier::ReasonForHalt => 100,
            PropertyIdentifier::RecipientList => 102,
            PropertyIdentifier::RecordCount => 141,
            PropertyIdentifier::RecordsSinceNotification => 140,
            PropertyIdentifier::ReferencePort => 483,
            PropertyIdentifier::RegisteredCarCall => 480,
            PropertyIdentifier::Reliability => 103,
            PropertyIdentifier::ReliabilityEvaluationInhibit => 357,
            PropertyIdentifier::RelinquishDefault => 104,
            PropertyIdentifier::Represents => 491,
            PropertyIdentifier::RequestedShedLevel => 218,
            PropertyIdentifier::RequestedUpdateInterval => 348,
            PropertyIdentifier::Required => 105,
            PropertyIdentifier::Resolution => 106,
            PropertyIdentifier::RestartNotificationRecipients => 202,
            PropertyIdentifier::RestoreCompletionTime => 340,
            PropertyIdentifier::RestorePreparationTime => 341,
            PropertyIdentifier::RoutingTable => 428,
            PropertyIdentifier::ScConnectWaitTimeout => 4194308,
            PropertyIdentifier::ScDirectConnectAcceptEnable => 4194309,
            PropertyIdentifier::ScDirectConnectAcceptUris => 4194310,
            PropertyIdentifier::ScDirectConnectBinding => 4194311,
            PropertyIdentifier::ScDirectConnectConnectionStatus => 4194312,
            PropertyIdentifier::ScDirectConnectInitiateEnable => 4194313,
            PropertyIdentifier::ScDisconnectWaitTimeout => 4194314,
            PropertyIdentifier::ScFailedConnectionRequests => 4194315,
            PropertyIdentifier::ScFailoverHubConnectionStatus => 4194316,
            PropertyIdentifier::ScFailoverHubUri => 4194317,
            PropertyIdentifier::ScHubConnectorState => 4194318,
            PropertyIdentifier::ScHubFunctionAcceptUris => 4194319,
            PropertyIdentifier::ScHubFunctionBinding => 4194320,
            PropertyIdentifier::ScHubFunctionConnectionStatus => 4194321,
            PropertyIdentifier::ScHubFunctionEnable => 4194322,
            PropertyIdentifier::ScHeartbeatTimeout => 4194323,
            PropertyIdentifier::ScPrimaryHubConnectionStatus => 4194324,
            PropertyIdentifier::ScPrimaryHubUri => 4194325,
            PropertyIdentifier::ScMaximumReconnectTime => 4194326,
            PropertyIdentifier::ScMinimumReconnectTime => 4194327,
            PropertyIdentifier::Scale => 187,
            PropertyIdentifier::ScaleFactor => 188,
            PropertyIdentifier::ScheduleDefault => 174,
            PropertyIdentifier::SecuredStatus => 235,
            PropertyIdentifier::SegmentationSupported => 107,
            PropertyIdentifier::SendNow => 505,
            PropertyIdentifier::SerialNumber => 372,
            PropertyIdentifier::Setpoint => 108,
            PropertyIdentifier::SetpointReference => 109,
            PropertyIdentifier::Setting => 162,
            PropertyIdentifier::ShedDuration => 219,
            PropertyIdentifier::ShedLevelDescriptions => 220,
            PropertyIdentifier::ShedLevels => 221,
            PropertyIdentifier::Silenced => 163,
            PropertyIdentifier::Stages => 494,
            PropertyIdentifier::StageNames => 495,
            PropertyIdentifier::StartTime => 142,
            PropertyIdentifier::StateChangeValues => 396,
            PropertyIdentifier::StateDescription => 222,
            PropertyIdentifier::StateText => 110,
            PropertyIdentifier::StatusFlags => 111,
            PropertyIdentifier::StopTime => 143,
            PropertyIdentifier::StopWhenFull => 144,
            PropertyIdentifier::StrikeCount => 391,
            PropertyIdentifier::StructuredObjectList => 209,
            PropertyIdentifier::SubordinateAddressBinding => 171,
            PropertyIdentifier::SubordinateAnnotations => 210,
            PropertyIdentifier::SubordinateList => 211,
            PropertyIdentifier::SubordinateNodeTypes => 487,
            PropertyIdentifier::SubordinateProxyEnable => 172,
            PropertyIdentifier::SubordinateRelationships => 489,
            PropertyIdentifier::SubordinateTags => 488,
            PropertyIdentifier::SubscribedRecipients => 362,
            PropertyIdentifier::SupportedFormatClasses => 305,
            PropertyIdentifier::SupportedFormats => 304,
            PropertyIdentifier::SystemStatus => 112,
            PropertyIdentifier::Tags => 486,
            PropertyIdentifier::TargetReferences => 496,
            PropertyIdentifier::ThreatAuthority => 306,
            PropertyIdentifier::ThreatLevel => 307,
            PropertyIdentifier::TimeDelay => 113,
            PropertyIdentifier::TimeDelayNormal => 356,
            PropertyIdentifier::TimeOfActiveTimeReset => 114,
            PropertyIdentifier::TimeOfDeviceRestart => 203,
            PropertyIdentifier::TimeOfStateCountReset => 115,
            PropertyIdentifier::TimeOfStrikeCountReset => 392,
            PropertyIdentifier::TimeSynchronizationInterval => 204,
            PropertyIdentifier::TimeSynchronizationRecipients => 116,
            PropertyIdentifier::TimerRunning => 397,
            PropertyIdentifier::TimerState => 398,
            PropertyIdentifier::TotalRecordCount => 145,
            PropertyIdentifier::TraceFlag => 308,
            PropertyIdentifier::TrackingValue => 164,
            PropertyIdentifier::TransactionNotificationClass => 309,
            PropertyIdentifier::Transition => 385,
            PropertyIdentifier::Trigger => 205,
            PropertyIdentifier::TrimFadeTime => 4194337,
            PropertyIdentifier::Units => 117,
            PropertyIdentifier::UpdateInterval => 118,
            PropertyIdentifier::UpdateTime => 189,
            PropertyIdentifier::UserExternalIdentifier => 310,
            PropertyIdentifier::UserInformationReference => 311,
            PropertyIdentifier::UserName => 317,
            PropertyIdentifier::UserType => 318,
            PropertyIdentifier::UsesRemaining => 319,
            PropertyIdentifier::UtcOffset => 119,
            PropertyIdentifier::UtcTimeSynchronizationRecipients => 206,
            PropertyIdentifier::ValidSamples => 146,
            PropertyIdentifier::ValueBeforeChange => 190,
            PropertyIdentifier::ValueChangeTime => 192,
            PropertyIdentifier::ValueSet => 191,
            PropertyIdentifier::ValueSource => 433,
            PropertyIdentifier::ValueSourceArray => 434,
            PropertyIdentifier::VarianceValue => 151,
            PropertyIdentifier::VendorIdentifier => 120,
            PropertyIdentifier::VendorName => 121,
            PropertyIdentifier::VerificationTime => 326,
            PropertyIdentifier::VirtualMacAddressTable => 429,
            PropertyIdentifier::VtClassesSupported => 122,
            PropertyIdentifier::WeeklySchedule => 123,
            PropertyIdentifier::WindowInterval => 147,
            PropertyIdentifier::WindowSamples => 148,
            PropertyIdentifier::WriteEveryScheduledAction => 4194333,
            PropertyIdentifier::WriteStatus => 370,
            PropertyIdentifier::ZoneFrom => 320,
            PropertyIdentifier::ZoneMembers => 165,
            PropertyIdentifier::ZoneTo => 321,
            PropertyIdentifier::Custom(val) => val,
        }
    }
}

impl From<u32> for PropertyIdentifier {
    fn from(val: u32) -> Self {
        match val {
            244 => Self::AbsenteeLimit,
            175 => Self::AcceptedModes,
            245 => Self::AccessAlarmEvents,
            246 => Self::AccessDoors,
            247 => Self::AccessEvent,
            248 => Self::AccessEventAuthenticationFactor,
            249 => Self::AccessEventCredential,
            322 => Self::AccessEventTag,
            250 => Self::AccessEventTime,
            251 => Self::AccessTransactionEvents,
            252 => Self::Accompaniment,
            253 => Self::AccompanimentTime,
            1 => Self::AckRequired,
            0 => Self::AckedTransitions,
            2 => Self::Action,
            3 => Self::ActionText,
            254 => Self::ActivationTime,
            255 => Self::ActiveAuthenticationPolicy,
            481 => Self::ActiveCovMultipleSubscriptions,
            152 => Self::ActiveCovSubscriptions,
            4 => Self::ActiveText,
            5 => Self::ActiveVtSessions,
            212 => Self::ActualShedLevel,
            508 => Self::AdditionalReferencePorts,
            176 => Self::AdjustValue,
            6 => Self::AlarmValue,
            7 => Self::AlarmValues,
            193 => Self::AlignIntervals,
            8 => Self::All,
            9 => Self::AllWritesSuccessful,
            365 => Self::AllowGroupDelayInhibit,
            399 => Self::ApduLength,
            10 => Self::ApduSegmentTimeout,
            11 => Self::ApduTimeout,
            12 => Self::ApplicationSoftwareVersion,
            13 => Self::Archive,
            256 => Self::AssignedAccessRights,
            447 => Self::AssignedLandingCalls,
            124 => Self::AttemptedSamples,
            497 => Self::AuditSourceReporter,
            498 => Self::AuditLevel,
            499 => Self::AuditNotificationRecipient,
            500 => Self::AuditPriorityFilter,
            501 => Self::AuditableOperations,
            257 => Self::AuthenticationFactors,
            258 => Self::AuthenticationPolicyList,
            259 => Self::AuthenticationPolicyNames,
            260 => Self::AuthenticationStatus,
            4194343 => Self::AuthorizationCache,
            364 => Self::AuthorizationExemptions,
            4194344 => Self::AuthorizationGroups,
            261 => Self::AuthorizationMode,
            4194345 => Self::AuthorizationPolicy,
            4194346 => Self::AuthorizationScope,
            4194347 => Self::AuthorizationServer,
            4194348 => Self::AuthorizationStatus,
            169 => Self::AutoSubordinateDiscovery,
            125 => Self::AverageValue,
            338 => Self::BackupAndRestoreState,
            153 => Self::BackupFailureTimeout,
            339 => Self::BackupPreparationTime,
            407 => Self::BacnetIpGlobalAddress,
            408 => Self::BacnetIpMode,
            409 => Self::BacnetIpMulticastAddress,
            410 => Self::BacnetIpNatTraversal,
            412 => Self::BacnetIpUdpPort,
            435 => Self::BacnetIpv6Mode,
            438 => Self::BacnetIpv6UdpPort,
            440 => Self::BacnetIpv6MulticastAddress,
            413 => Self::BbmdAcceptFdRegistrations,
            414 => Self::BbmdBroadcastDistributionTable,
            415 => Self::BbmdForeignDeviceTable,
            262 => Self::BelongsTo,
            14 => Self::Bias,
            342 => Self::BitMask,
            343 => Self::BitText,
            373 => Self::BlinkWarnEnable,
            126 => Self::BufferSize,
            448 => Self::CarAssignedDirection,
            449 => Self::CarDoorCommand,
            450 => Self::CarDoorStatus,
            451 => Self::CarDoorText,
            452 => Self::CarDoorZone,
            453 => Self::CarDriveStatus,
            454 => Self::CarLoad,
            455 => Self::CarLoadUnits,
            456 => Self::CarMode,
            457 => Self::CarMovingDirection,
            458 => Self::CarPosition,
            509 => Self::CertificateSigningRequestFile,
            15 => Self::ChangeOfStateCount,
            16 => Self::ChangeOfStateTime,
            416 => Self::ChangesPending,
            366 => Self::ChannelNumber,
            127 => Self::ClientCovIncrement,
            4194334 => Self::ColorCommand,
            4194328 => Self::ColorOverride,
            4194329 => Self::ColorReference,
            417 => Self::Command,
            430 => Self::CommandTimeArray,
            510 => Self::CommandValidationResult,
            154 => Self::ConfigurationFiles,
            367 => Self::ControlGroups,
            19 => Self::ControlledVariableReference,
            20 => Self::ControlledVariableUnits,
            21 => Self::ControlledVariableValue,
            177 => Self::Count,
            178 => Self::CountBeforeChange,
            179 => Self::CountChangeTime,
            22 => Self::CovIncrement,
            180 => Self::CovPeriod,
            128 => Self::CovResubscriptionInterval,
            349 => Self::CovuPeriod,
            350 => Self::CovuRecipients,
            263 => Self::CredentialDisable,
            264 => Self::CredentialStatus,
            265 => Self::Credentials,
            266 => Self::CredentialsInZone,
            431 => Self::CurrentCommandPriority,
            4194307 => Self::CurrentHealth,
            155 => Self::DatabaseRevision,
            23 => Self::DateList,
            24 => Self::DaylightSavingsStatus,
            267 => Self::DaysRemaining,
            25 => Self::Deadband,
            4194330 => Self::DefaultColor,
            4194331 => Self::DefaultColorTemperature,
            374 => Self::DefaultFadeTime,
            492 => Self::DefaultPresentValue,
            375 => Self::DefaultRampRate,
            376 => Self::DefaultStepIncrement,
            490 => Self::DefaultSubordinateRelationship,
            393 => Self::DefaultTimeout,
            502 => Self::DeleteOnForward,
            4194341 => Self::DefaultOnValue,
            484 => Self::DeployedProfileLocation,
            26 => Self::DerivativeConstant,
            27 => Self::DerivativeConstantUnits,
            28 => Self::Description,
            29 => Self::DescriptionOfHalt,
            30 => Self::DeviceAddressBinding,
            4194338 => Self::DeviceAddressProxyEnable,
            4194339 => Self::DeviceAddressProxyTable,
            4194340 => Self::DeviceAddressProxyTimeout,
            31 => Self::DeviceType,
            507 => Self::DeviceUuid,
            156 => Self::DirectReading,
            226 => Self::DoorAlarmState,
            227 => Self::DoorExtendedPulseTime,
            228 => Self::DoorMembers,
            229 => Self::DoorOpenTooLongTime,
            230 => Self::DoorPulseTime,
            231 => Self::DoorStatus,
            232 => Self::DoorUnlockDelayTime,
            213 => Self::DutyWindow,
            32 => Self::EffectivePeriod,
            386 => Self::EgressActive,
            377 => Self::EgressTime,
            33 => Self::ElapsedActiveTime,
            459 => Self::ElevatorGroup,
            133 => Self::Enable,
            460 => Self::EnergyMeter,
            461 => Self::EnergyMeterRef,
            268 => Self::EntryPoints,
            34 => Self::ErrorLimit,
            462 => Self::EscalatorMode,
            354 => Self::EventAlgorithmInhibit,
            355 => Self::EventAlgorithmInhibitRef,
            353 => Self::EventDetectionEnable,
            35 => Self::EventEnable,
            351 => Self::EventMessageTexts,
            352 => Self::EventMessageTextsConfig,
            83 => Self::EventParameters,
            36 => Self::EventState,
            130 => Self::EventTimeStamps,
            37 => Self::EventType,
            38 => Self::ExceptionSchedule,
            368 => Self::ExecutionDelay,
            269 => Self::ExitPoints,
            214 => Self::ExpectedShedLevel,
            270 => Self::ExpirationTime,
            271 => Self::ExtendedTimeEnable,
            272 => Self::FailedAttemptEvents,
            273 => Self::FailedAttempts,
            274 => Self::FailedAttemptsTime,
            388 => Self::FaultHighLimit,
            389 => Self::FaultLowLimit,
            358 => Self::FaultParameters,
            463 => Self::FaultSignals,
            359 => Self::FaultType,
            39 => Self::FaultValues,
            418 => Self::FdBbmdAddress,
            419 => Self::FdSubscriptionLifetime,
            40 => Self::FeedbackValue,
            41 => Self::FileAccessMethod,
            42 => Self::FileSize,
            43 => Self::FileType,
            44 => Self::FirmwareRevision,
            506 => Self::FloorNumber,
            464 => Self::FloorText,
            215 => Self::FullDutyBaseline,
            323 => Self::GlobalIdentifier,
            465 => Self::GroupId,
            346 => Self::GroupMemberNames,
            345 => Self::GroupMembers,
            467 => Self::GroupMode,
            4194335 => Self::HighEndTrim,
            45 => Self::HighLimit,
            468 => Self::HigherDeck,
            47 => Self::InProcess,
            378 => Self::InProgress,
            46 => Self::InactiveText,
            394 => Self::InitialTimeout,
            181 => Self::InputReference,
            469 => Self::InstallationId,
            48 => Self::InstanceOf,
            379 => Self::InstantaneousPower,
            49 => Self::IntegralConstant,
            50 => Self::IntegralConstantUnits,
            387 => Self::InterfaceValue,
            195 => Self::IntervalOffset,
            400 => Self::IpAddress,
            401 => Self::IpDefaultGateway,
            402 => Self::IpDhcpEnable,
            403 => Self::IpDhcpLeaseTime,
            404 => Self::IpDhcpLeaseTimeRemaining,
            405 => Self::IpDhcpServer,
            406 => Self::IpDnsServer,
            411 => Self::IpSubnetMask,
            436 => Self::Ipv6Address,
            442 => Self::Ipv6AutoAddressingEnable,
            439 => Self::Ipv6DefaultGateway,
            443 => Self::Ipv6DhcpLeaseTime,
            444 => Self::Ipv6DhcpLeaseTimeRemaining,
            445 => Self::Ipv6DhcpServer,
            441 => Self::Ipv6DnsServer,
            437 => Self::Ipv6PrefixLength,
            446 => Self::Ipv6ZoneIndex,
            51 => Self::IssueConfirmedNotifications,
            511 => Self::IssuerCertificateFiles,
            344 => Self::IsUtc,
            471 => Self::LandingCallControl,
            470 => Self::LandingCalls,
            472 => Self::LandingDoorStatus,
            275 => Self::LastAccessEvent,
            276 => Self::LastAccessPoint,
            432 => Self::LastCommandTime,
            277 => Self::LastCredentialAdded,
            278 => Self::LastCredentialAddedTime,
            279 => Self::LastCredentialRemoved,
            280 => Self::LastCredentialRemovedTime,
            173 => Self::LastNotifyRecord,
            4194342 => Self::LastOnValue,
            369 => Self::LastPriority,
            196 => Self::LastRestartReason,
            157 => Self::LastRestoreTime,
            395 => Self::LastStateChange,
            281 => Self::LastUseTime,
            166 => Self::LifeSafetyAlarmValues,
            380 => Self::LightingCommand,
            381 => Self::LightingCommandDefaultPriority,
            52 => Self::LimitEnable,
            182 => Self::LimitMonitoringInterval,
            420 => Self::LinkSpeed,
            422 => Self::LinkSpeedAutonegotiate,
            421 => Self::LinkSpeeds,
            53 => Self::ListOfGroupMembers,
            54 => Self::ListOfObjectPropertyReferences,
            56 => Self::LocalDate,
            360 => Self::LocalForwardingOnly,
            57 => Self::LocalTime,
            58 => Self::Location,
            233 => Self::LockStatus,
            282 => Self::Lockout,
            283 => Self::LockoutRelinquishTime,
            131 => Self::LogBuffer,
            132 => Self::LogDeviceObjectProperty,
            134 => Self::LogInterval,
            183 => Self::LoggingObject,
            184 => Self::LoggingRecord,
            197 => Self::LoggingType,
            390 => Self::LowDiffLimit,
            4194336 => Self::LowEndTrim,
            59 => Self::LowLimit,
            473 => Self::LowerDeck,
            423 => Self::MacAddress,
            474 => Self::MachineRoomId,
            158 => Self::MaintenanceRequired,
            475 => Self::MakingCarCall,
            60 => Self::ManipulatedVariableReference,
            170 => Self::ManualSubordinateAddressBinding,
            234 => Self::MaskedAlarmValues,
            382 => Self::MaxActualValue,
            62 => Self::MaxApduLengthAccepted,
            4194304 => Self::MaxBvlcLengthAccepted,
            285 => Self::MaxFailedAttempts,
            4194349 => Self::MaxProxiedIAmsPerSecond,
            63 => Self::MaxInfoFrames,
            64 => Self::MaxManager,
            4194305 => Self::MaxNpduLengthAccepted,
            65 => Self::MaxPresValue,
            167 => Self::MaxSegmentsAccepted,
            61 => Self::MaximumOutput,
            503 => Self::MaximumSendDelay,
            135 => Self::MaximumValue,
            149 => Self::MaximumValueTimestamp,
            159 => Self::MemberOf,
            347 => Self::MemberStatusFlags,
            286 => Self::Members,
            383 => Self::MinActualValue,
            69 => Self::MinPresValue,
            66 => Self::MinimumOffTime,
            67 => Self::MinimumOnTime,
            68 => Self::MinimumOutput,
            136 => Self::MinimumValue,
            150 => Self::MinimumValueTimestamp,
            160 => Self::Mode,
            70 => Self::ModelName,
            71 => Self::ModificationDate,
            504 => Self::MonitoredObjects,
            287 => Self::MusterPoint,
            288 => Self::NegativeAccessRules,
            424 => Self::NetworkInterfaceName,
            425 => Self::NetworkNumber,
            426 => Self::NetworkNumberQuality,
            427 => Self::NetworkType,
            476 => Self::NextStoppingFloor,
            207 => Self::NodeSubtype,
            208 => Self::NodeType,
            17 => Self::NotificationClass,
            137 => Self::NotificationThreshold,
            72 => Self::NotifyType,
            73 => Self::NumberOfApduRetries,
            289 => Self::NumberOfAuthenticationPolicies,
            74 => Self::NumberOfStates,
            75 => Self::ObjectIdentifier,
            76 => Self::ObjectList,
            77 => Self::ObjectName,
            78 => Self::ObjectPropertyReference,
            79 => Self::ObjectType,
            290 => Self::OccupancyCount,
            291 => Self::OccupancyCountAdjust,
            292 => Self::OccupancyCountEnable,
            294 => Self::OccupancyLowerLimit,
            295 => Self::OccupancyLowerLimitEnforced,
            296 => Self::OccupancyState,
            297 => Self::OccupancyUpperLimit,
            298 => Self::OccupancyUpperLimitEnforced,
            477 => Self::OperationDirection,
            161 => Self::OperationExpected,
            4194306 => Self::OperationalCertificateFile,
            80 => Self::Optional,
            81 => Self::OutOfService,
            82 => Self::OutputUnits,
            4194332 => Self::OverrideColorReference,
            300 => Self::PassbackMode,
            301 => Self::PassbackTimeout,
            478 => Self::PassengerAlarm,
            84 => Self::Polarity,
            363 => Self::PortFilter,
            302 => Self::PositiveAccessRules,
            384 => Self::Power,
            479 => Self::PowerMode,
            185 => Self::Prescale,
            493 => Self::PresentStage,
            85 => Self::PresentValue,
            86 => Self::Priority,
            87 => Self::PriorityArray,
            88 => Self::PriorityForWriting,
            89 => Self::ProcessIdentifier,
            361 => Self::ProcessIdentifierFilter,
            485 => Self::ProfileLocation,
            168 => Self::ProfileName,
            90 => Self::ProgramChange,
            91 => Self::ProgramLocation,
            92 => Self::ProgramState,
            371 => Self::PropertyList,
            93 => Self::ProportionalConstant,
            94 => Self::ProportionalConstantUnits,
            482 => Self::ProtocolLevel,
            96 => Self::ProtocolObjectTypesSupported,
            139 => Self::ProtocolRevision,
            97 => Self::ProtocolServicesSupported,
            98 => Self::ProtocolVersion,
            186 => Self::PulseRate,
            99 => Self::ReadOnly,
            303 => Self::ReasonForDisable,
            100 => Self::ReasonForHalt,
            102 => Self::RecipientList,
            141 => Self::RecordCount,
            140 => Self::RecordsSinceNotification,
            483 => Self::ReferencePort,
            480 => Self::RegisteredCarCall,
            103 => Self::Reliability,
            357 => Self::ReliabilityEvaluationInhibit,
            104 => Self::RelinquishDefault,
            491 => Self::Represents,
            218 => Self::RequestedShedLevel,
            348 => Self::RequestedUpdateInterval,
            105 => Self::Required,
            106 => Self::Resolution,
            202 => Self::RestartNotificationRecipients,
            340 => Self::RestoreCompletionTime,
            341 => Self::RestorePreparationTime,
            428 => Self::RoutingTable,
            4194308 => Self::ScConnectWaitTimeout,
            4194309 => Self::ScDirectConnectAcceptEnable,
            4194310 => Self::ScDirectConnectAcceptUris,
            4194311 => Self::ScDirectConnectBinding,
            4194312 => Self::ScDirectConnectConnectionStatus,
            4194313 => Self::ScDirectConnectInitiateEnable,
            4194314 => Self::ScDisconnectWaitTimeout,
            4194315 => Self::ScFailedConnectionRequests,
            4194316 => Self::ScFailoverHubConnectionStatus,
            4194317 => Self::ScFailoverHubUri,
            4194318 => Self::ScHubConnectorState,
            4194319 => Self::ScHubFunctionAcceptUris,
            4194320 => Self::ScHubFunctionBinding,
            4194321 => Self::ScHubFunctionConnectionStatus,
            4194322 => Self::ScHubFunctionEnable,
            4194323 => Self::ScHeartbeatTimeout,
            4194324 => Self::ScPrimaryHubConnectionStatus,
            4194325 => Self::ScPrimaryHubUri,
            4194326 => Self::ScMaximumReconnectTime,
            4194327 => Self::ScMinimumReconnectTime,
            187 => Self::Scale,
            188 => Self::ScaleFactor,
            174 => Self::ScheduleDefault,
            235 => Self::SecuredStatus,
            107 => Self::SegmentationSupported,
            505 => Self::SendNow,
            372 => Self::SerialNumber,
            108 => Self::Setpoint,
            109 => Self::SetpointReference,
            162 => Self::Setting,
            219 => Self::ShedDuration,
            220 => Self::ShedLevelDescriptions,
            221 => Self::ShedLevels,
            163 => Self::Silenced,
            494 => Self::Stages,
            495 => Self::StageNames,
            142 => Self::StartTime,
            396 => Self::StateChangeValues,
            222 => Self::StateDescription,
            110 => Self::StateText,
            111 => Self::StatusFlags,
            143 => Self::StopTime,
            144 => Self::StopWhenFull,
            391 => Self::StrikeCount,
            209 => Self::StructuredObjectList,
            171 => Self::SubordinateAddressBinding,
            210 => Self::SubordinateAnnotations,
            211 => Self::SubordinateList,
            487 => Self::SubordinateNodeTypes,
            172 => Self::SubordinateProxyEnable,
            489 => Self::SubordinateRelationships,
            488 => Self::SubordinateTags,
            362 => Self::SubscribedRecipients,
            305 => Self::SupportedFormatClasses,
            304 => Self::SupportedFormats,
            112 => Self::SystemStatus,
            486 => Self::Tags,
            496 => Self::TargetReferences,
            306 => Self::ThreatAuthority,
            307 => Self::ThreatLevel,
            113 => Self::TimeDelay,
            356 => Self::TimeDelayNormal,
            114 => Self::TimeOfActiveTimeReset,
            203 => Self::TimeOfDeviceRestart,
            115 => Self::TimeOfStateCountReset,
            392 => Self::TimeOfStrikeCountReset,
            204 => Self::TimeSynchronizationInterval,
            116 => Self::TimeSynchronizationRecipients,
            397 => Self::TimerRunning,
            398 => Self::TimerState,
            145 => Self::TotalRecordCount,
            308 => Self::TraceFlag,
            164 => Self::TrackingValue,
            309 => Self::TransactionNotificationClass,
            385 => Self::Transition,
            205 => Self::Trigger,
            4194337 => Self::TrimFadeTime,
            117 => Self::Units,
            118 => Self::UpdateInterval,
            189 => Self::UpdateTime,
            310 => Self::UserExternalIdentifier,
            311 => Self::UserInformationReference,
            317 => Self::UserName,
            318 => Self::UserType,
            319 => Self::UsesRemaining,
            119 => Self::UtcOffset,
            206 => Self::UtcTimeSynchronizationRecipients,
            146 => Self::ValidSamples,
            190 => Self::ValueBeforeChange,
            192 => Self::ValueChangeTime,
            191 => Self::ValueSet,
            433 => Self::ValueSource,
            434 => Self::ValueSourceArray,
            151 => Self::VarianceValue,
            120 => Self::VendorIdentifier,
            121 => Self::VendorName,
            326 => Self::VerificationTime,
            429 => Self::VirtualMacAddressTable,
            122 => Self::VtClassesSupported,
            123 => Self::WeeklySchedule,
            147 => Self::WindowInterval,
            148 => Self::WindowSamples,
            4194333 => Self::WriteEveryScheduledAction,
            370 => Self::WriteStatus,
            320 => Self::ZoneFrom,
            165 => Self::ZoneMembers,
            321 => Self::ZoneTo,
            val => Self::Custom(val),
        }
    }
}
