use bacnet_macros::BacnetEnum;

/// BACnet property identifiers see clause 21.6 of the BACnet specification.
#[derive(BacnetEnum, Debug, PartialEq, Eq, Clone, Copy)]
#[bacnet_enum(u32)]
pub enum PropertyIdentifier {
    #[bacnet_value(244)]
    AbsenteeLimit,
    #[bacnet_value(175)]
    AcceptedModes,
    #[bacnet_value(245)]
    AccessAlarmEvents,
    #[bacnet_value(246)]
    AccessDoors,
    #[bacnet_value(247)]
    AccessEvent,
    #[bacnet_value(248)]
    AccessEventAuthenticationFactor,
    #[bacnet_value(249)]
    AccessEventCredential,
    #[bacnet_value(322)]
    AccessEventTag,
    #[bacnet_value(250)]
    AccessEventTime,
    #[bacnet_value(251)]
    AccessTransactionEvents,
    #[bacnet_value(252)]
    Accompaniment,
    #[bacnet_value(253)]
    AccompanimentTime,
    #[bacnet_value(1)]
    AckRequired,
    #[bacnet_value(0)]
    AckedTransitions,
    #[bacnet_value(2)]
    Action,
    #[bacnet_value(3)]
    ActionText,
    #[bacnet_value(254)]
    ActivationTime,
    #[bacnet_value(255)]
    ActiveAuthenticationPolicy,
    #[bacnet_value(481)]
    ActiveCovMultipleSubscriptions,
    #[bacnet_value(152)]
    ActiveCovSubscriptions,
    #[bacnet_value(4)]
    ActiveText,
    #[bacnet_value(5)]
    ActiveVtSessions,
    #[bacnet_value(212)]
    ActualShedLevel,
    #[bacnet_value(508)]
    AdditionalReferencePorts,
    #[bacnet_value(176)]
    AdjustValue,
    #[bacnet_value(6)]
    AlarmValue,
    #[bacnet_value(7)]
    AlarmValues,
    #[bacnet_value(193)]
    AlignIntervals,
    #[bacnet_value(8)]
    All,
    #[bacnet_value(9)]
    AllWritesSuccessful,
    #[bacnet_value(365)]
    AllowGroupDelayInhibit,
    #[bacnet_value(399)]
    ApduLength,
    #[bacnet_value(10)]
    ApduSegmentTimeout,
    #[bacnet_value(11)]
    ApduTimeout,
    #[bacnet_value(12)]
    ApplicationSoftwareVersion,
    #[bacnet_value(13)]
    Archive,
    #[bacnet_value(256)]
    AssignedAccessRights,
    #[bacnet_value(447)]
    AssignedLandingCalls,
    #[bacnet_value(124)]
    AttemptedSamples,
    #[bacnet_value(497)]
    AuditSourceReporter,
    #[bacnet_value(498)]
    AuditLevel,
    #[bacnet_value(499)]
    AuditNotificationRecipient,
    #[bacnet_value(500)]
    AuditPriorityFilter,
    #[bacnet_value(501)]
    AuditableOperations,
    #[bacnet_value(257)]
    AuthenticationFactors,
    #[bacnet_value(258)]
    AuthenticationPolicyList,
    #[bacnet_value(259)]
    AuthenticationPolicyNames,
    #[bacnet_value(260)]
    AuthenticationStatus,
    #[bacnet_value(4194343)]
    AuthorizationCache,
    #[bacnet_value(364)]
    AuthorizationExemptions,
    #[bacnet_value(4194344)]
    AuthorizationGroups,
    #[bacnet_value(261)]
    AuthorizationMode,
    #[bacnet_value(4194345)]
    AuthorizationPolicy,
    #[bacnet_value(4194346)]
    AuthorizationScope,
    #[bacnet_value(4194347)]
    AuthorizationServer,
    #[bacnet_value(4194348)]
    AuthorizationStatus,
    #[bacnet_value(169)]
    AutoSubordinateDiscovery,
    #[bacnet_value(125)]
    AverageValue,
    #[bacnet_value(338)]
    BackupAndRestoreState,
    #[bacnet_value(153)]
    BackupFailureTimeout,
    #[bacnet_value(339)]
    BackupPreparationTime,
    #[bacnet_value(407)]
    BacnetIpGlobalAddress,
    #[bacnet_value(408)]
    BacnetIpMode,
    #[bacnet_value(409)]
    BacnetIpMulticastAddress,
    #[bacnet_value(410)]
    BacnetIpNatTraversal,
    #[bacnet_value(412)]
    BacnetIpUdpPort,
    #[bacnet_value(435)]
    BacnetIpv6Mode,
    #[bacnet_value(438)]
    BacnetIpv6UdpPort,
    #[bacnet_value(440)]
    BacnetIpv6MulticastAddress,
    #[bacnet_value(413)]
    BbmdAcceptFdRegistrations,
    #[bacnet_value(414)]
    BbmdBroadcastDistributionTable,
    #[bacnet_value(415)]
    BbmdForeignDeviceTable,
    #[bacnet_value(262)]
    BelongsTo,
    #[bacnet_value(14)]
    Bias,
    #[bacnet_value(342)]
    BitMask,
    #[bacnet_value(343)]
    BitText,
    #[bacnet_value(373)]
    BlinkWarnEnable,
    #[bacnet_value(126)]
    BufferSize,
    #[bacnet_value(448)]
    CarAssignedDirection,
    #[bacnet_value(449)]
    CarDoorCommand,
    #[bacnet_value(450)]
    CarDoorStatus,
    #[bacnet_value(451)]
    CarDoorText,
    #[bacnet_value(452)]
    CarDoorZone,
    #[bacnet_value(453)]
    CarDriveStatus,
    #[bacnet_value(454)]
    CarLoad,
    #[bacnet_value(455)]
    CarLoadUnits,
    #[bacnet_value(456)]
    CarMode,
    #[bacnet_value(457)]
    CarMovingDirection,
    #[bacnet_value(458)]
    CarPosition,
    #[bacnet_value(509)]
    CertificateSigningRequestFile,
    #[bacnet_value(15)]
    ChangeOfStateCount,
    #[bacnet_value(16)]
    ChangeOfStateTime,
    #[bacnet_value(416)]
    ChangesPending,
    #[bacnet_value(366)]
    ChannelNumber,
    #[bacnet_value(127)]
    ClientCovIncrement,
    #[bacnet_value(4194334)]
    ColorCommand,
    #[bacnet_value(4194328)]
    ColorOverride,
    #[bacnet_value(4194329)]
    ColorReference,
    #[bacnet_value(417)]
    Command,
    #[bacnet_value(430)]
    CommandTimeArray,
    #[bacnet_value(510)]
    CommandValidationResult,
    #[bacnet_value(154)]
    ConfigurationFiles,
    #[bacnet_value(367)]
    ControlGroups,
    #[bacnet_value(19)]
    ControlledVariableReference,
    #[bacnet_value(20)]
    ControlledVariableUnits,
    #[bacnet_value(21)]
    ControlledVariableValue,
    #[bacnet_value(177)]
    Count,
    #[bacnet_value(178)]
    CountBeforeChange,
    #[bacnet_value(179)]
    CountChangeTime,
    #[bacnet_value(22)]
    CovIncrement,
    #[bacnet_value(180)]
    CovPeriod,
    #[bacnet_value(128)]
    CovResubscriptionInterval,
    #[bacnet_value(349)]
    CovuPeriod,
    #[bacnet_value(350)]
    CovuRecipients,
    #[bacnet_value(263)]
    CredentialDisable,
    #[bacnet_value(264)]
    CredentialStatus,
    #[bacnet_value(265)]
    Credentials,
    #[bacnet_value(266)]
    CredentialsInZone,
    #[bacnet_value(431)]
    CurrentCommandPriority,
    #[bacnet_value(4194307)]
    CurrentHealth,
    #[bacnet_value(155)]
    DatabaseRevision,
    #[bacnet_value(23)]
    DateList,
    #[bacnet_value(24)]
    DaylightSavingsStatus,
    #[bacnet_value(267)]
    DaysRemaining,
    #[bacnet_value(25)]
    Deadband,
    #[bacnet_value(4194330)]
    DefaultColor,
    #[bacnet_value(4194331)]
    DefaultColorTemperature,
    #[bacnet_value(374)]
    DefaultFadeTime,
    #[bacnet_value(492)]
    DefaultPresentValue,
    #[bacnet_value(375)]
    DefaultRampRate,
    #[bacnet_value(376)]
    DefaultStepIncrement,
    #[bacnet_value(490)]
    DefaultSubordinateRelationship,
    #[bacnet_value(393)]
    DefaultTimeout,
    #[bacnet_value(502)]
    DeleteOnForward,
    #[bacnet_value(4194341)]
    DefaultOnValue,
    #[bacnet_value(484)]
    DeployedProfileLocation,
    #[bacnet_value(26)]
    DerivativeConstant,
    #[bacnet_value(27)]
    DerivativeConstantUnits,
    #[bacnet_value(28)]
    Description,
    #[bacnet_value(29)]
    DescriptionOfHalt,
    #[bacnet_value(30)]
    DeviceAddressBinding,
    #[bacnet_value(4194338)]
    DeviceAddressProxyEnable,
    #[bacnet_value(4194339)]
    DeviceAddressProxyTable,
    #[bacnet_value(4194340)]
    DeviceAddressProxyTimeout,
    #[bacnet_value(31)]
    DeviceType,
    #[bacnet_value(507)]
    DeviceUuid,
    #[bacnet_value(156)]
    DirectReading,
    #[bacnet_value(226)]
    DoorAlarmState,
    #[bacnet_value(227)]
    DoorExtendedPulseTime,
    #[bacnet_value(228)]
    DoorMembers,
    #[bacnet_value(229)]
    DoorOpenTooLongTime,
    #[bacnet_value(230)]
    DoorPulseTime,
    #[bacnet_value(231)]
    DoorStatus,
    #[bacnet_value(232)]
    DoorUnlockDelayTime,
    #[bacnet_value(213)]
    DutyWindow,
    #[bacnet_value(32)]
    EffectivePeriod,
    #[bacnet_value(386)]
    EgressActive,
    #[bacnet_value(377)]
    EgressTime,
    #[bacnet_value(33)]
    ElapsedActiveTime,
    #[bacnet_value(459)]
    ElevatorGroup,
    #[bacnet_value(133)]
    Enable,
    #[bacnet_value(460)]
    EnergyMeter,
    #[bacnet_value(461)]
    EnergyMeterRef,
    #[bacnet_value(268)]
    EntryPoints,
    #[bacnet_value(34)]
    ErrorLimit,
    #[bacnet_value(462)]
    EscalatorMode,
    #[bacnet_value(354)]
    EventAlgorithmInhibit,
    #[bacnet_value(355)]
    EventAlgorithmInhibitRef,
    #[bacnet_value(353)]
    EventDetectionEnable,
    #[bacnet_value(35)]
    EventEnable,
    #[bacnet_value(351)]
    EventMessageTexts,
    #[bacnet_value(352)]
    EventMessageTextsConfig,
    #[bacnet_value(83)]
    EventParameters,
    #[bacnet_value(36)]
    EventState,
    #[bacnet_value(130)]
    EventTimeStamps,
    #[bacnet_value(37)]
    EventType,
    #[bacnet_value(38)]
    ExceptionSchedule,
    #[bacnet_value(368)]
    ExecutionDelay,
    #[bacnet_value(269)]
    ExitPoints,
    #[bacnet_value(214)]
    ExpectedShedLevel,
    #[bacnet_value(270)]
    ExpirationTime,
    #[bacnet_value(271)]
    ExtendedTimeEnable,
    #[bacnet_value(272)]
    FailedAttemptEvents,
    #[bacnet_value(273)]
    FailedAttempts,
    #[bacnet_value(274)]
    FailedAttemptsTime,
    #[bacnet_value(388)]
    FaultHighLimit,
    #[bacnet_value(389)]
    FaultLowLimit,
    #[bacnet_value(358)]
    FaultParameters,
    #[bacnet_value(463)]
    FaultSignals,
    #[bacnet_value(359)]
    FaultType,
    #[bacnet_value(39)]
    FaultValues,
    #[bacnet_value(418)]
    FdBbmdAddress,
    #[bacnet_value(419)]
    FdSubscriptionLifetime,
    #[bacnet_value(40)]
    FeedbackValue,
    #[bacnet_value(41)]
    FileAccessMethod,
    #[bacnet_value(42)]
    FileSize,
    #[bacnet_value(43)]
    FileType,
    #[bacnet_value(44)]
    FirmwareRevision,
    #[bacnet_value(506)]
    FloorNumber,
    #[bacnet_value(464)]
    FloorText,
    #[bacnet_value(215)]
    FullDutyBaseline,
    #[bacnet_value(323)]
    GlobalIdentifier,
    #[bacnet_value(465)]
    GroupId,
    #[bacnet_value(346)]
    GroupMemberNames,
    #[bacnet_value(345)]
    GroupMembers,
    #[bacnet_value(467)]
    GroupMode,
    #[bacnet_value(4194335)]
    HighEndTrim,
    #[bacnet_value(45)]
    HighLimit,
    #[bacnet_value(468)]
    HigherDeck,
    #[bacnet_value(47)]
    InProcess,
    #[bacnet_value(378)]
    InProgress,
    #[bacnet_value(46)]
    InactiveText,
    #[bacnet_value(394)]
    InitialTimeout,
    #[bacnet_value(181)]
    InputReference,
    #[bacnet_value(469)]
    InstallationId,
    #[bacnet_value(48)]
    InstanceOf,
    #[bacnet_value(379)]
    InstantaneousPower,
    #[bacnet_value(49)]
    IntegralConstant,
    #[bacnet_value(50)]
    IntegralConstantUnits,
    #[bacnet_value(387)]
    InterfaceValue,
    #[bacnet_value(195)]
    IntervalOffset,
    #[bacnet_value(400)]
    IpAddress,
    #[bacnet_value(401)]
    IpDefaultGateway,
    #[bacnet_value(402)]
    IpDhcpEnable,
    #[bacnet_value(403)]
    IpDhcpLeaseTime,
    #[bacnet_value(404)]
    IpDhcpLeaseTimeRemaining,
    #[bacnet_value(405)]
    IpDhcpServer,
    #[bacnet_value(406)]
    IpDnsServer,
    #[bacnet_value(411)]
    IpSubnetMask,
    #[bacnet_value(436)]
    Ipv6Address,
    #[bacnet_value(442)]
    Ipv6AutoAddressingEnable,
    #[bacnet_value(439)]
    Ipv6DefaultGateway,
    #[bacnet_value(443)]
    Ipv6DhcpLeaseTime,
    #[bacnet_value(444)]
    Ipv6DhcpLeaseTimeRemaining,
    #[bacnet_value(445)]
    Ipv6DhcpServer,
    #[bacnet_value(441)]
    Ipv6DnsServer,
    #[bacnet_value(437)]
    Ipv6PrefixLength,
    #[bacnet_value(446)]
    Ipv6ZoneIndex,
    #[bacnet_value(51)]
    IssueConfirmedNotifications,
    #[bacnet_value(511)]
    IssuerCertificateFiles,
    #[bacnet_value(344)]
    IsUtc,
    #[bacnet_value(471)]
    LandingCallControl,
    #[bacnet_value(470)]
    LandingCalls,
    #[bacnet_value(472)]
    LandingDoorStatus,
    #[bacnet_value(275)]
    LastAccessEvent,
    #[bacnet_value(276)]
    LastAccessPoint,
    #[bacnet_value(432)]
    LastCommandTime,
    #[bacnet_value(277)]
    LastCredentialAdded,
    #[bacnet_value(278)]
    LastCredentialAddedTime,
    #[bacnet_value(279)]
    LastCredentialRemoved,
    #[bacnet_value(280)]
    LastCredentialRemovedTime,
    #[bacnet_value(173)]
    LastNotifyRecord,
    #[bacnet_value(4194342)]
    LastOnValue,
    #[bacnet_value(369)]
    LastPriority,
    #[bacnet_value(196)]
    LastRestartReason,
    #[bacnet_value(157)]
    LastRestoreTime,
    #[bacnet_value(395)]
    LastStateChange,
    #[bacnet_value(281)]
    LastUseTime,
    #[bacnet_value(166)]
    LifeSafetyAlarmValues,
    #[bacnet_value(380)]
    LightingCommand,
    #[bacnet_value(381)]
    LightingCommandDefaultPriority,
    #[bacnet_value(52)]
    LimitEnable,
    #[bacnet_value(182)]
    LimitMonitoringInterval,
    #[bacnet_value(420)]
    LinkSpeed,
    #[bacnet_value(422)]
    LinkSpeedAutonegotiate,
    #[bacnet_value(421)]
    LinkSpeeds,
    #[bacnet_value(53)]
    ListOfGroupMembers,
    #[bacnet_value(54)]
    ListOfObjectPropertyReferences,
    #[bacnet_value(56)]
    LocalDate,
    #[bacnet_value(360)]
    LocalForwardingOnly,
    #[bacnet_value(57)]
    LocalTime,
    #[bacnet_value(58)]
    Location,
    #[bacnet_value(233)]
    LockStatus,
    #[bacnet_value(282)]
    Lockout,
    #[bacnet_value(283)]
    LockoutRelinquishTime,
    #[bacnet_value(131)]
    LogBuffer,
    #[bacnet_value(132)]
    LogDeviceObjectProperty,
    #[bacnet_value(134)]
    LogInterval,
    #[bacnet_value(183)]
    LoggingObject,
    #[bacnet_value(184)]
    LoggingRecord,
    #[bacnet_value(197)]
    LoggingType,
    #[bacnet_value(390)]
    LowDiffLimit,
    #[bacnet_value(4194336)]
    LowEndTrim,
    #[bacnet_value(59)]
    LowLimit,
    #[bacnet_value(473)]
    LowerDeck,
    #[bacnet_value(423)]
    MacAddress,
    #[bacnet_value(474)]
    MachineRoomId,
    #[bacnet_value(158)]
    MaintenanceRequired,
    #[bacnet_value(475)]
    MakingCarCall,
    #[bacnet_value(60)]
    ManipulatedVariableReference,
    #[bacnet_value(170)]
    ManualSubordinateAddressBinding,
    #[bacnet_value(234)]
    MaskedAlarmValues,
    #[bacnet_value(382)]
    MaxActualValue,
    #[bacnet_value(62)]
    MaxApduLengthAccepted,
    #[bacnet_value(4194304)]
    MaxBvlcLengthAccepted,
    #[bacnet_value(285)]
    MaxFailedAttempts,
    #[bacnet_value(4194349)]
    MaxProxiedIAmsPerSecond,
    #[bacnet_value(63)]
    MaxInfoFrames,
    #[bacnet_value(64)]
    MaxManager,
    #[bacnet_value(4194305)]
    MaxNpduLengthAccepted,
    #[bacnet_value(65)]
    MaxPresValue,
    #[bacnet_value(167)]
    MaxSegmentsAccepted,
    #[bacnet_value(61)]
    MaximumOutput,
    #[bacnet_value(503)]
    MaximumSendDelay,
    #[bacnet_value(135)]
    MaximumValue,
    #[bacnet_value(149)]
    MaximumValueTimestamp,
    #[bacnet_value(159)]
    MemberOf,
    #[bacnet_value(347)]
    MemberStatusFlags,
    #[bacnet_value(286)]
    Members,
    #[bacnet_value(383)]
    MinActualValue,
    #[bacnet_value(69)]
    MinPresValue,
    #[bacnet_value(66)]
    MinimumOffTime,
    #[bacnet_value(67)]
    MinimumOnTime,
    #[bacnet_value(68)]
    MinimumOutput,
    #[bacnet_value(136)]
    MinimumValue,
    #[bacnet_value(150)]
    MinimumValueTimestamp,
    #[bacnet_value(160)]
    Mode,
    #[bacnet_value(70)]
    ModelName,
    #[bacnet_value(71)]
    ModificationDate,
    #[bacnet_value(504)]
    MonitoredObjects,
    #[bacnet_value(287)]
    MusterPoint,
    #[bacnet_value(288)]
    NegativeAccessRules,
    #[bacnet_value(424)]
    NetworkInterfaceName,
    #[bacnet_value(425)]
    NetworkNumber,
    #[bacnet_value(426)]
    NetworkNumberQuality,
    #[bacnet_value(427)]
    NetworkType,
    #[bacnet_value(476)]
    NextStoppingFloor,
    #[bacnet_value(207)]
    NodeSubtype,
    #[bacnet_value(208)]
    NodeType,
    #[bacnet_value(17)]
    NotificationClass,
    #[bacnet_value(137)]
    NotificationThreshold,
    #[bacnet_value(72)]
    NotifyType,
    #[bacnet_value(73)]
    NumberOfApduRetries,
    #[bacnet_value(289)]
    NumberOfAuthenticationPolicies,
    #[bacnet_value(74)]
    NumberOfStates,
    #[bacnet_value(75)]
    ObjectIdentifier,
    #[bacnet_value(76)]
    ObjectList,
    #[bacnet_value(77)]
    ObjectName,
    #[bacnet_value(78)]
    ObjectPropertyReference,
    #[bacnet_value(79)]
    ObjectType,
    #[bacnet_value(290)]
    OccupancyCount,
    #[bacnet_value(291)]
    OccupancyCountAdjust,
    #[bacnet_value(292)]
    OccupancyCountEnable,
    #[bacnet_value(294)]
    OccupancyLowerLimit,
    #[bacnet_value(295)]
    OccupancyLowerLimitEnforced,
    #[bacnet_value(296)]
    OccupancyState,
    #[bacnet_value(297)]
    OccupancyUpperLimit,
    #[bacnet_value(298)]
    OccupancyUpperLimitEnforced,
    #[bacnet_value(477)]
    OperationDirection,
    #[bacnet_value(161)]
    OperationExpected,
    #[bacnet_value(4194306)]
    OperationalCertificateFile,
    #[bacnet_value(80)]
    Optional,
    #[bacnet_value(81)]
    OutOfService,
    #[bacnet_value(82)]
    OutputUnits,
    #[bacnet_value(4194332)]
    OverrideColorReference,
    #[bacnet_value(300)]
    PassbackMode,
    #[bacnet_value(301)]
    PassbackTimeout,
    #[bacnet_value(478)]
    PassengerAlarm,
    #[bacnet_value(84)]
    Polarity,
    #[bacnet_value(363)]
    PortFilter,
    #[bacnet_value(302)]
    PositiveAccessRules,
    #[bacnet_value(384)]
    Power,
    #[bacnet_value(479)]
    PowerMode,
    #[bacnet_value(185)]
    Prescale,
    #[bacnet_value(493)]
    PresentStage,
    #[bacnet_value(85)]
    PresentValue,
    #[bacnet_value(86)]
    Priority,
    #[bacnet_value(87)]
    PriorityArray,
    #[bacnet_value(88)]
    PriorityForWriting,
    #[bacnet_value(89)]
    ProcessIdentifier,
    #[bacnet_value(361)]
    ProcessIdentifierFilter,
    #[bacnet_value(485)]
    ProfileLocation,
    #[bacnet_value(168)]
    ProfileName,
    #[bacnet_value(90)]
    ProgramChange,
    #[bacnet_value(91)]
    ProgramLocation,
    #[bacnet_value(92)]
    ProgramState,
    #[bacnet_value(371)]
    PropertyList,
    #[bacnet_value(93)]
    ProportionalConstant,
    #[bacnet_value(94)]
    ProportionalConstantUnits,
    #[bacnet_value(482)]
    ProtocolLevel,
    #[bacnet_value(96)]
    ProtocolObjectTypesSupported,
    #[bacnet_value(139)]
    ProtocolRevision,
    #[bacnet_value(97)]
    ProtocolServicesSupported,
    #[bacnet_value(98)]
    ProtocolVersion,
    #[bacnet_value(186)]
    PulseRate,
    #[bacnet_value(99)]
    ReadOnly,
    #[bacnet_value(303)]
    ReasonForDisable,
    #[bacnet_value(100)]
    ReasonForHalt,
    #[bacnet_value(102)]
    RecipientList,
    #[bacnet_value(141)]
    RecordCount,
    #[bacnet_value(140)]
    RecordsSinceNotification,
    #[bacnet_value(483)]
    ReferencePort,
    #[bacnet_value(480)]
    RegisteredCarCall,
    #[bacnet_value(103)]
    Reliability,
    #[bacnet_value(357)]
    ReliabilityEvaluationInhibit,
    #[bacnet_value(104)]
    RelinquishDefault,
    #[bacnet_value(491)]
    Represents,
    #[bacnet_value(218)]
    RequestedShedLevel,
    #[bacnet_value(348)]
    RequestedUpdateInterval,
    #[bacnet_value(105)]
    Required,
    #[bacnet_value(106)]
    Resolution,
    #[bacnet_value(202)]
    RestartNotificationRecipients,
    #[bacnet_value(340)]
    RestoreCompletionTime,
    #[bacnet_value(341)]
    RestorePreparationTime,
    #[bacnet_value(428)]
    RoutingTable,
    #[bacnet_value(4194308)]
    ScConnectWaitTimeout,
    #[bacnet_value(4194309)]
    ScDirectConnectAcceptEnable,
    #[bacnet_value(4194310)]
    ScDirectConnectAcceptUris,
    #[bacnet_value(4194311)]
    ScDirectConnectBinding,
    #[bacnet_value(4194312)]
    ScDirectConnectConnectionStatus,
    #[bacnet_value(4194313)]
    ScDirectConnectInitiateEnable,
    #[bacnet_value(4194314)]
    ScDisconnectWaitTimeout,
    #[bacnet_value(4194315)]
    ScFailedConnectionRequests,
    #[bacnet_value(4194316)]
    ScFailoverHubConnectionStatus,
    #[bacnet_value(4194317)]
    ScFailoverHubUri,
    #[bacnet_value(4194318)]
    ScHubConnectorState,
    #[bacnet_value(4194319)]
    ScHubFunctionAcceptUris,
    #[bacnet_value(4194320)]
    ScHubFunctionBinding,
    #[bacnet_value(4194321)]
    ScHubFunctionConnectionStatus,
    #[bacnet_value(4194322)]
    ScHubFunctionEnable,
    #[bacnet_value(4194323)]
    ScHeartbeatTimeout,
    #[bacnet_value(4194324)]
    ScPrimaryHubConnectionStatus,
    #[bacnet_value(4194325)]
    ScPrimaryHubUri,
    #[bacnet_value(4194326)]
    ScMaximumReconnectTime,
    #[bacnet_value(4194327)]
    ScMinimumReconnectTime,
    #[bacnet_value(187)]
    Scale,
    #[bacnet_value(188)]
    ScaleFactor,
    #[bacnet_value(174)]
    ScheduleDefault,
    #[bacnet_value(235)]
    SecuredStatus,
    #[bacnet_value(107)]
    SegmentationSupported,
    #[bacnet_value(505)]
    SendNow,
    #[bacnet_value(372)]
    SerialNumber,
    #[bacnet_value(108)]
    Setpoint,
    #[bacnet_value(109)]
    SetpointReference,
    #[bacnet_value(162)]
    Setting,
    #[bacnet_value(219)]
    ShedDuration,
    #[bacnet_value(220)]
    ShedLevelDescriptions,
    #[bacnet_value(221)]
    ShedLevels,
    #[bacnet_value(163)]
    Silenced,
    #[bacnet_value(494)]
    Stages,
    #[bacnet_value(495)]
    StageNames,
    #[bacnet_value(142)]
    StartTime,
    #[bacnet_value(396)]
    StateChangeValues,
    #[bacnet_value(222)]
    StateDescription,
    #[bacnet_value(110)]
    StateText,
    #[bacnet_value(111)]
    StatusFlags,
    #[bacnet_value(143)]
    StopTime,
    #[bacnet_value(144)]
    StopWhenFull,
    #[bacnet_value(391)]
    StrikeCount,
    #[bacnet_value(209)]
    StructuredObjectList,
    #[bacnet_value(171)]
    SubordinateAddressBinding,
    #[bacnet_value(210)]
    SubordinateAnnotations,
    #[bacnet_value(211)]
    SubordinateList,
    #[bacnet_value(487)]
    SubordinateNodeTypes,
    #[bacnet_value(172)]
    SubordinateProxyEnable,
    #[bacnet_value(489)]
    SubordinateRelationships,
    #[bacnet_value(488)]
    SubordinateTags,
    #[bacnet_value(362)]
    SubscribedRecipients,
    #[bacnet_value(305)]
    SupportedFormatClasses,
    #[bacnet_value(304)]
    SupportedFormats,
    #[bacnet_value(112)]
    SystemStatus,
    #[bacnet_value(486)]
    Tags,
    #[bacnet_value(496)]
    TargetReferences,
    #[bacnet_value(306)]
    ThreatAuthority,
    #[bacnet_value(307)]
    ThreatLevel,
    #[bacnet_value(113)]
    TimeDelay,
    #[bacnet_value(356)]
    TimeDelayNormal,
    #[bacnet_value(114)]
    TimeOfActiveTimeReset,
    #[bacnet_value(203)]
    TimeOfDeviceRestart,
    #[bacnet_value(115)]
    TimeOfStateCountReset,
    #[bacnet_value(392)]
    TimeOfStrikeCountReset,
    #[bacnet_value(204)]
    TimeSynchronizationInterval,
    #[bacnet_value(116)]
    TimeSynchronizationRecipients,
    #[bacnet_value(397)]
    TimerRunning,
    #[bacnet_value(398)]
    TimerState,
    #[bacnet_value(145)]
    TotalRecordCount,
    #[bacnet_value(308)]
    TraceFlag,
    #[bacnet_value(164)]
    TrackingValue,
    #[bacnet_value(309)]
    TransactionNotificationClass,
    #[bacnet_value(385)]
    Transition,
    #[bacnet_value(205)]
    Trigger,
    #[bacnet_value(4194337)]
    TrimFadeTime,
    #[bacnet_value(117)]
    Units,
    #[bacnet_value(118)]
    UpdateInterval,
    #[bacnet_value(189)]
    UpdateTime,
    #[bacnet_value(310)]
    UserExternalIdentifier,
    #[bacnet_value(311)]
    UserInformationReference,
    #[bacnet_value(317)]
    UserName,
    #[bacnet_value(318)]
    UserType,
    #[bacnet_value(319)]
    UsesRemaining,
    #[bacnet_value(119)]
    UtcOffset,
    #[bacnet_value(206)]
    UtcTimeSynchronizationRecipients,
    #[bacnet_value(146)]
    ValidSamples,
    #[bacnet_value(190)]
    ValueBeforeChange,
    #[bacnet_value(192)]
    ValueChangeTime,
    #[bacnet_value(191)]
    ValueSet,
    #[bacnet_value(433)]
    ValueSource,
    #[bacnet_value(434)]
    ValueSourceArray,
    #[bacnet_value(151)]
    VarianceValue,
    #[bacnet_value(120)]
    VendorIdentifier,
    #[bacnet_value(121)]
    VendorName,
    #[bacnet_value(326)]
    VerificationTime,
    #[bacnet_value(429)]
    VirtualMacAddressTable,
    #[bacnet_value(122)]
    VtClassesSupported,
    #[bacnet_value(123)]
    WeeklySchedule,
    #[bacnet_value(147)]
    WindowInterval,
    #[bacnet_value(148)]
    WindowSamples,
    #[bacnet_value(4194333)]
    WriteEveryScheduledAction,
    #[bacnet_value(370)]
    WriteStatus,
    #[bacnet_value(320)]
    ZoneFrom,
    #[bacnet_value(165)]
    ZoneMembers,
    #[bacnet_value(321)]
    ZoneTo,
    Custom(u32),
}
